//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RechnerPlus.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RechnerPlus.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The modern calculator for Android, Windows and Linux with Scientific mode and Unit Converter. ähnelt.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RechnerPlus ähnelt.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open browser. Please check your internet connection. ähnelt.
        /// </summary>
        public static string BrowserError {
            get {
                return ResourceManager.GetString("BrowserError", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press again to exit ähnelt.
        /// </summary>
        public static string BackPressToExit {
            get {
                return ResourceManager.GetString("BackPressToExit", resourceCulture) ?? "Press again to exit";
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angle ähnelt.
        /// </summary>
        public static string CategoryAngle {
            get {
                return ResourceManager.GetString("CategoryAngle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area ähnelt.
        /// </summary>
        public static string CategoryArea {
            get {
                return ResourceManager.GetString("CategoryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string CategoryData {
            get {
                return ResourceManager.GetString("CategoryData", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energy ähnelt.
        /// </summary>
        public static string CategoryEnergy {
            get {
                return ResourceManager.GetString("CategoryEnergy", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pressure ähnelt.
        /// </summary>
        public static string CategoryPressure {
            get {
                return ResourceManager.GetString("CategoryPressure", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length ähnelt.
        /// </summary>
        public static string CategoryLength {
            get {
                return ResourceManager.GetString("CategoryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        public static string CategorySpeed {
            get {
                return ResourceManager.GetString("CategorySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature ähnelt.
        /// </summary>
        public static string CategoryTemperature {
            get {
                return ResourceManager.GetString("CategoryTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string CategoryTime {
            get {
                return ResourceManager.GetString("CategoryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        public static string CategoryVolume {
            get {
                return ResourceManager.GetString("CategoryVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weight ähnelt.
        /// </summary>
        public static string CategoryWeight {
            get {
                return ResourceManager.GetString("CategoryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear History ähnelt.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard empty ähnelt.
        /// </summary>
        public static string ClipboardEmpty {
            get {
                return ResourceManager.GetString("ClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string ConverterCategory {
            get {
                return ResourceManager.GetString("ConverterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From ähnelt.
        /// </summary>
        public static string ConverterFrom {
            get {
                return ResourceManager.GetString("ConverterFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit Converter ähnelt.
        /// </summary>
        public static string ConverterTitle {
            get {
                return ResourceManager.GetString("ConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To ähnelt.
        /// </summary>
        public static string ConverterTo {
            get {
                return ResourceManager.GetString("ConverterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy failed ähnelt.
        /// </summary>
        public static string CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied to clipboard ähnelt.
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression too long ähnelt.
        /// </summary>
        public static string ExpressionTooLong {
            get {
                return ResourceManager.GetString("ExpressionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factorial: Value must be between 0 and 170 ähnelt.
        /// </summary>
        public static string FactorialRangeError {
            get {
                return ResourceManager.GetString("FactorialRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send Feedback ähnelt.
        /// </summary>
        public static string FeedbackButton {
            get {
                return ResourceManager.GetString("FeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basic ähnelt.
        /// </summary>
        public static string ModeBasic {
            get {
                return ResourceManager.GetString("ModeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scientific ähnelt.
        /// </summary>
        public static string ModeScientific {
            get {
                return ResourceManager.GetString("ModeScientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculator ähnelt.
        /// </summary>
        public static string NavCalculator {
            get {
                return ResourceManager.GetString("NavCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Converter ähnelt.
        /// </summary>
        public static string NavConverter {
            get {
                return ResourceManager.GetString("NavConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No calculations yet ähnelt.
        /// </summary>
        public static string NoCalculationsYet {
            get {
                return ResourceManager.GetString("NoCalculationsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste failed ähnelt.
        /// </summary>
        public static string PasteFailed {
            get {
                return ResourceManager.GetString("PasteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid number ähnelt.
        /// </summary>
        public static string PasteInvalidNumber {
            get {
                return ResourceManager.GetString("PasteInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pasted ähnelt.
        /// </summary>
        public static string PasteSuccess {
            get {
                return ResourceManager.GetString("PasteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://sites.google.com/rs-digital.org/rechnerplus/startseite ähnelt.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About the App ähnelt.
        /// </summary>
        public static string SettingsAboutApp {
            get {
                return ResourceManager.GetString("SettingsAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Design ähnelt.
        /// </summary>
        public static string SettingsChooseDesign {
            get {
                return ResourceManager.GetString("SettingsChooseDesign", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        public static string SettingsDecimalAuto {
            get {
                return ResourceManager.GetString("SettingsDecimalAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decimal Places ähnelt.
        /// </summary>
        public static string SettingsDecimalPlaces {
            get {
                return ResourceManager.GetString("SettingsDecimalPlaces", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haptic Feedback ähnelt.
        /// </summary>
        public static string SettingsHaptic {
            get {
                return ResourceManager.GetString("SettingsHaptic", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number Format ähnelt.
        /// </summary>
        public static string SettingsNumberFormat {
            get {
                return ResourceManager.GetString("SettingsNumberFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aurora ähnelt.
        /// </summary>
        public static string ThemeAurora {
            get {
                return ResourceManager.GetString("ThemeAurora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colorful dark ähnelt.
        /// </summary>
        public static string ThemeAuroraDesc {
            get {
                return ResourceManager.GetString("ThemeAuroraDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daylight ähnelt.
        /// </summary>
        public static string ThemeDaylight {
            get {
                return ResourceManager.GetString("ThemeDaylight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean and light ähnelt.
        /// </summary>
        public static string ThemeDaylightDesc {
            get {
                return ResourceManager.GetString("ThemeDaylightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest ähnelt.
        /// </summary>
        public static string ThemeForest {
            get {
                return ResourceManager.GetString("ThemeForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Natural dark ähnelt.
        /// </summary>
        public static string ThemeForestDesc {
            get {
                return ResourceManager.GetString("ThemeForestDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tangent undefined ähnelt.
        /// </summary>
        public static string TangentUndefined {
            get {
                return ResourceManager.GetString("TangentUndefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Midnight ähnelt.
        /// </summary>
        public static string ThemeMidnight {
            get {
                return ResourceManager.GetString("ThemeMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modern dark ähnelt.
        /// </summary>
        public static string ThemeMidnightDesc {
            get {
                return ResourceManager.GetString("ThemeMidnightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acre ähnelt.
        /// </summary>
        public static string UnitAcre {
            get {
                return ResourceManager.GetString("UnitAcre", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arcminute ähnelt.
        /// </summary>
        public static string UnitArcminute {
            get {
                return ResourceManager.GetString("UnitArcminute", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arcsecond ähnelt.
        /// </summary>
        public static string UnitArcsecond {
            get {
                return ResourceManager.GetString("UnitArcsecond", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Atmosphere ähnelt.
        /// </summary>
        public static string UnitAtmosphere {
            get {
                return ResourceManager.GetString("UnitAtmosphere", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bar ähnelt.
        /// </summary>
        public static string UnitBar {
            get {
                return ResourceManager.GetString("UnitBar", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit ähnelt.
        /// </summary>
        public static string UnitBit {
            get {
                return ResourceManager.GetString("UnitBit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BTU ähnelt.
        /// </summary>
        public static string UnitBTU {
            get {
                return ResourceManager.GetString("UnitBTU", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Byte ähnelt.
        /// </summary>
        public static string UnitByte {
            get {
                return ResourceManager.GetString("UnitByte", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calorie ähnelt.
        /// </summary>
        public static string UnitCalorie {
            get {
                return ResourceManager.GetString("UnitCalorie", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Celsius ähnelt.
        /// </summary>
        public static string UnitCelsius {
            get {
                return ResourceManager.GetString("UnitCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Centimeter ähnelt.
        /// </summary>
        public static string UnitCentimeter {
            get {
                return ResourceManager.GetString("UnitCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cubic Meter ähnelt.
        /// </summary>
        public static string UnitCubicMeter {
            get {
                return ResourceManager.GetString("UnitCubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cup ähnelt.
        /// </summary>
        public static string UnitCup {
            get {
                return ResourceManager.GetString("UnitCup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        public static string UnitDays {
            get {
                return ResourceManager.GetString("UnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Degree ähnelt.
        /// </summary>
        public static string UnitDegree {
            get {
                return ResourceManager.GetString("UnitDegree", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrenheit ähnelt.
        /// </summary>
        public static string UnitFahrenheit {
            get {
                return ResourceManager.GetString("UnitFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foot ähnelt.
        /// </summary>
        public static string UnitFoot {
            get {
                return ResourceManager.GetString("UnitFoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fluid Ounce (US) ähnelt.
        /// </summary>
        public static string UnitFluidOunceUS {
            get {
                return ResourceManager.GetString("UnitFluidOunceUS", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gallon (US) ähnelt.
        /// </summary>
        public static string UnitGallonUS {
            get {
                return ResourceManager.GetString("UnitGallonUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gigabyte ähnelt.
        /// </summary>
        public static string UnitGigabyte {
            get {
                return ResourceManager.GetString("UnitGigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gradian ähnelt.
        /// </summary>
        public static string UnitGradian {
            get {
                return ResourceManager.GetString("UnitGradian", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gram ähnelt.
        /// </summary>
        public static string UnitGram {
            get {
                return ResourceManager.GetString("UnitGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hectare ähnelt.
        /// </summary>
        public static string UnitHectare {
            get {
                return ResourceManager.GetString("UnitHectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        public static string UnitHours {
            get {
                return ResourceManager.GetString("UnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inch ähnelt.
        /// </summary>
        public static string UnitInch {
            get {
                return ResourceManager.GetString("UnitInch", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Joule ähnelt.
        /// </summary>
        public static string UnitJoule {
            get {
                return ResourceManager.GetString("UnitJoule", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kelvin ähnelt.
        /// </summary>
        public static string UnitKelvin {
            get {
                return ResourceManager.GetString("UnitKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilobyte ähnelt.
        /// </summary>
        public static string UnitKilobyte {
            get {
                return ResourceManager.GetString("UnitKilobyte", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilocalorie ähnelt.
        /// </summary>
        public static string UnitKilocalorie {
            get {
                return ResourceManager.GetString("UnitKilocalorie", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilogram ähnelt.
        /// </summary>
        public static string UnitKilogram {
            get {
                return ResourceManager.GetString("UnitKilogram", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilojoule ähnelt.
        /// </summary>
        public static string UnitKilojoule {
            get {
                return ResourceManager.GetString("UnitKilojoule", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilometer ähnelt.
        /// </summary>
        public static string UnitKilometer {
            get {
                return ResourceManager.GetString("UnitKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilometers per Hour ähnelt.
        /// </summary>
        public static string UnitKilometersPerHour {
            get {
                return ResourceManager.GetString("UnitKilometersPerHour", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilopascal ähnelt.
        /// </summary>
        public static string UnitKilopascal {
            get {
                return ResourceManager.GetString("UnitKilopascal", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilowatt Hour ähnelt.
        /// </summary>
        public static string UnitKilowattHour {
            get {
                return ResourceManager.GetString("UnitKilowattHour", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knots ähnelt.
        /// </summary>
        public static string UnitKnots {
            get {
                return ResourceManager.GetString("UnitKnots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liter ähnelt.
        /// </summary>
        public static string UnitLiter {
            get {
                return ResourceManager.GetString("UnitLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Megabyte ähnelt.
        /// </summary>
        public static string UnitMegabyte {
            get {
                return ResourceManager.GetString("UnitMegabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meter ähnelt.
        /// </summary>
        public static string UnitMeter {
            get {
                return ResourceManager.GetString("UnitMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meters per Second ähnelt.
        /// </summary>
        public static string UnitMetersPerSecond {
            get {
                return ResourceManager.GetString("UnitMetersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Micrometer ähnelt.
        /// </summary>
        public static string UnitMicrometer {
            get {
                return ResourceManager.GetString("UnitMicrometer", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mile ähnelt.
        /// </summary>
        public static string UnitMile {
            get {
                return ResourceManager.GetString("UnitMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miles per Hour ähnelt.
        /// </summary>
        public static string UnitMilesPerHour {
            get {
                return ResourceManager.GetString("UnitMilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milligram ähnelt.
        /// </summary>
        public static string UnitMilligram {
            get {
                return ResourceManager.GetString("UnitMilligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliliter ähnelt.
        /// </summary>
        public static string UnitMilliliter {
            get {
                return ResourceManager.GetString("UnitMilliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Millimeter ähnelt.
        /// </summary>
        public static string UnitMillimeter {
            get {
                return ResourceManager.GetString("UnitMillimeter", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Millimeter Mercury ähnelt.
        /// </summary>
        public static string UnitMillimeterMercury {
            get {
                return ResourceManager.GetString("UnitMillimeterMercury", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliseconds ähnelt.
        /// </summary>
        public static string UnitMilliseconds {
            get {
                return ResourceManager.GetString("UnitMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        public static string UnitMinutes {
            get {
                return ResourceManager.GetString("UnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nautical Mile ähnelt.
        /// </summary>
        public static string UnitNauticalMile {
            get {
                return ResourceManager.GetString("UnitNauticalMile", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ounce ähnelt.
        /// </summary>
        public static string UnitOunce {
            get {
                return ResourceManager.GetString("UnitOunce", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pascal ähnelt.
        /// </summary>
        public static string UnitPascal {
            get {
                return ResourceManager.GetString("UnitPascal", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pint (US) ähnelt.
        /// </summary>
        public static string UnitPintUS {
            get {
                return ResourceManager.GetString("UnitPintUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pound ähnelt.
        /// </summary>
        public static string UnitPound {
            get {
                return ResourceManager.GetString("UnitPound", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PSI ähnelt.
        /// </summary>
        public static string UnitPSI {
            get {
                return ResourceManager.GetString("UnitPSI", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quart (US) ähnelt.
        /// </summary>
        public static string UnitQuartUS {
            get {
                return ResourceManager.GetString("UnitQuartUS", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seconds ähnelt.
        /// </summary>
        public static string UnitSeconds {
            get {
                return ResourceManager.GetString("UnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Square Foot ähnelt.
        /// </summary>
        public static string UnitSquareFoot {
            get {
                return ResourceManager.GetString("UnitSquareFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Square Kilometer ähnelt.
        /// </summary>
        public static string UnitSquareKilometer {
            get {
                return ResourceManager.GetString("UnitSquareKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Square Meter ähnelt.
        /// </summary>
        public static string UnitSquareMeter {
            get {
                return ResourceManager.GetString("UnitSquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stone ähnelt.
        /// </summary>
        public static string UnitStone {
            get {
                return ResourceManager.GetString("UnitStone", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tablespoon ähnelt.
        /// </summary>
        public static string UnitTablespoon {
            get {
                return ResourceManager.GetString("UnitTablespoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teaspoon ähnelt.
        /// </summary>
        public static string UnitTeaspoon {
            get {
                return ResourceManager.GetString("UnitTeaspoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terabyte ähnelt.
        /// </summary>
        public static string UnitTerabyte {
            get {
                return ResourceManager.GetString("UnitTerabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tonne ähnelt.
        /// </summary>
        public static string UnitTonne {
            get {
                return ResourceManager.GetString("UnitTonne", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn ähnelt.
        /// </summary>
        public static string UnitTurn {
            get {
                return ResourceManager.GetString("UnitTurn", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watt Hour ähnelt.
        /// </summary>
        public static string UnitWattHour {
            get {
                return ResourceManager.GetString("UnitWattHour", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weeks ähnelt.
        /// </summary>
        public static string UnitWeeks {
            get {
                return ResourceManager.GetString("UnitWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yard ähnelt.
        /// </summary>
        public static string UnitYard {
            get {
                return ResourceManager.GetString("UnitYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        public static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
