//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRechner.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessRechner.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string ActivityActive {
            get {
                return ResourceManager.GetString("ActivityActive", resourceCulture);
            }
        }

        public static string ActivityLevel {
            get {
                return ResourceManager.GetString("ActivityLevel", resourceCulture);
            }
        }

        public static string ActivityLight {
            get {
                return ResourceManager.GetString("ActivityLight", resourceCulture);
            }
        }

        public static string ActivityMinutes {
            get {
                return ResourceManager.GetString("ActivityMinutes", resourceCulture);
            }
        }

        public static string ActivityModerate {
            get {
                return ResourceManager.GetString("ActivityModerate", resourceCulture);
            }
        }

        public static string ActivitySedentary {
            get {
                return ResourceManager.GetString("ActivitySedentary", resourceCulture);
            }
        }

        public static string ActivityVeryActive {
            get {
                return ResourceManager.GetString("ActivityVeryActive", resourceCulture);
            }
        }

        public static string ActivityWater {
            get {
                return ResourceManager.GetString("ActivityWater", resourceCulture);
            }
        }

        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        public static string AddBmi {
            get {
                return ResourceManager.GetString("AddBmi", resourceCulture);
            }
        }

        public static string AddBodyFat {
            get {
                return ResourceManager.GetString("AddBodyFat", resourceCulture);
            }
        }

        public static string AddFood {
            get {
                return ResourceManager.GetString("AddFood", resourceCulture);
            }
        }

        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }

        public static string AddWeight {
            get {
                return ResourceManager.GetString("AddWeight", resourceCulture);
            }
        }

        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }

        public static string AlertCalorieGoalSaved {
            get {
                return ResourceManager.GetString("AlertCalorieGoalSaved", resourceCulture);
            }
        }

        public static string AlertCalculateFirst {
            get {
                return ResourceManager.GetString("AlertCalculateFirst", resourceCulture);
            }
        }

        public static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }

        public static string AlertNoPurchases {
            get {
                return ResourceManager.GetString("AlertNoPurchases", resourceCulture);
            }
        }

        public static string AlertPurchaseRestored {
            get {
                return ResourceManager.GetString("AlertPurchaseRestored", resourceCulture);
            }
        }

        public static string AlertPurchaseSuccess {
            get {
                return ResourceManager.GetString("AlertPurchaseSuccess", resourceCulture);
            }
        }

        public static string AlertSavedToTracking {
            get {
                return ResourceManager.GetString("AlertSavedToTracking", resourceCulture);
            }
        }

        public static string AlertSaveError {
            get {
                return ResourceManager.GetString("AlertSaveError", resourceCulture);
            }
        }

        public static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }

        public static string AlertWaterGoalSaved {
            get {
                return ResourceManager.GetString("AlertWaterGoalSaved", resourceCulture);
            }
        }

        public static string AmountGrams {
            get {
                return ResourceManager.GetString("AmountGrams", resourceCulture);
            }
        }

        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }

        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }

        public static string AverageWeight {
            get {
                return ResourceManager.GetString("AverageWeight", resourceCulture);
            }
        }

        public static string BarcodeScannerDescription {
            get {
                return ResourceManager.GetString("BarcodeScannerDescription", resourceCulture);
            }
        }

        public static string BarcodeScannerTitle {
            get {
                return ResourceManager.GetString("BarcodeScannerTitle", resourceCulture);
            }
        }

        public static string BaseWater {
            get {
                return ResourceManager.GetString("BaseWater", resourceCulture);
            }
        }

        public static string BenefitHistory {
            get {
                return ResourceManager.GetString("BenefitHistory", resourceCulture);
            }
        }

        public static string BenefitNoAds {
            get {
                return ResourceManager.GetString("BenefitNoAds", resourceCulture);
            }
        }

        public static string BenefitScanner {
            get {
                return ResourceManager.GetString("BenefitScanner", resourceCulture);
            }
        }

        public static string BenefitTracking {
            get {
                return ResourceManager.GetString("BenefitTracking", resourceCulture);
            }
        }

        public static string Bmr {
            get {
                return ResourceManager.GetString("Bmr", resourceCulture);
            }
        }

        public static string BmiEntries {
            get {
                return ResourceManager.GetString("BmiEntries", resourceCulture);
            }
        }

        public static string BmiMildUnderweight {
            get {
                return ResourceManager.GetString("BmiMildUnderweight", resourceCulture);
            }
        }

        public static string BmiModerateUnderweight {
            get {
                return ResourceManager.GetString("BmiModerateUnderweight", resourceCulture);
            }
        }

        public static string BmiNormal {
            get {
                return ResourceManager.GetString("BmiNormal", resourceCulture);
            }
        }

        public static string BmiNormalRange {
            get {
                return ResourceManager.GetString("BmiNormalRange", resourceCulture);
            }
        }

        public static string BmiObeseClass1 {
            get {
                return ResourceManager.GetString("BmiObeseClass1", resourceCulture);
            }
        }

        public static string BmiObeseClass2 {
            get {
                return ResourceManager.GetString("BmiObeseClass2", resourceCulture);
            }
        }

        public static string BmiObeseClass3 {
            get {
                return ResourceManager.GetString("BmiObeseClass3", resourceCulture);
            }
        }

        public static string BmiOverweight {
            get {
                return ResourceManager.GetString("BmiOverweight", resourceCulture);
            }
        }

        public static string BmiSevereUnderweight {
            get {
                return ResourceManager.GetString("BmiSevereUnderweight", resourceCulture);
            }
        }

        public static string BmiStats30Days {
            get {
                return ResourceManager.GetString("BmiStats30Days", resourceCulture);
            }
        }

        public static string BmiTrend {
            get {
                return ResourceManager.GetString("BmiTrend", resourceCulture);
            }
        }

        public static string BmiValue {
            get {
                return ResourceManager.GetString("BmiValue", resourceCulture);
            }
        }

        public static string BodyComposition {
            get {
                return ResourceManager.GetString("BodyComposition", resourceCulture);
            }
        }

        public static string BodyFat {
            get {
                return ResourceManager.GetString("BodyFat", resourceCulture);
            }
        }

        public static string BodyFatAthletes {
            get {
                return ResourceManager.GetString("BodyFatAthletes", resourceCulture);
            }
        }

        public static string BodyFatAverage {
            get {
                return ResourceManager.GetString("BodyFatAverage", resourceCulture);
            }
        }

        public static string BodyFatEntries {
            get {
                return ResourceManager.GetString("BodyFatEntries", resourceCulture);
            }
        }

        public static string BodyFatEssential {
            get {
                return ResourceManager.GetString("BodyFatEssential", resourceCulture);
            }
        }

        public static string BodyFatFitness {
            get {
                return ResourceManager.GetString("BodyFatFitness", resourceCulture);
            }
        }

        public static string BodyFatHealthyRange {
            get {
                return ResourceManager.GetString("BodyFatHealthyRange", resourceCulture);
            }
        }

        public static string BodyFatObese {
            get {
                return ResourceManager.GetString("BodyFatObese", resourceCulture);
            }
        }

        public static string BodyFatPercent {
            get {
                return ResourceManager.GetString("BodyFatPercent", resourceCulture);
            }
        }

        public static string BodyFatStats30Days {
            get {
                return ResourceManager.GetString("BodyFatStats30Days", resourceCulture);
            }
        }

        public static string BodyFatTrend {
            get {
                return ResourceManager.GetString("BodyFatTrend", resourceCulture);
            }
        }

        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }

        public static string CalcBmi {
            get {
                return ResourceManager.GetString("CalcBmi", resourceCulture);
            }
        }

        public static string CalcBmiDesc {
            get {
                return ResourceManager.GetString("CalcBmiDesc", resourceCulture);
            }
        }

        public static string CalcBodyFat {
            get {
                return ResourceManager.GetString("CalcBodyFat", resourceCulture);
            }
        }

        public static string CalcBodyFatDesc {
            get {
                return ResourceManager.GetString("CalcBodyFatDesc", resourceCulture);
            }
        }

        public static string CalcCalories {
            get {
                return ResourceManager.GetString("CalcCalories", resourceCulture);
            }
        }

        public static string CalcCaloriesDesc {
            get {
                return ResourceManager.GetString("CalcCaloriesDesc", resourceCulture);
            }
        }

        public static string CalcIdealWeight {
            get {
                return ResourceManager.GetString("CalcIdealWeight", resourceCulture);
            }
        }

        public static string CalcIdealWeightDesc {
            get {
                return ResourceManager.GetString("CalcIdealWeightDesc", resourceCulture);
            }
        }

        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }

        public static string Calculators {
            get {
                return ResourceManager.GetString("Calculators", resourceCulture);
            }
        }

        public static string CalcWater {
            get {
                return ResourceManager.GetString("CalcWater", resourceCulture);
            }
        }

        public static string CalcWaterDesc {
            get {
                return ResourceManager.GetString("CalcWaterDesc", resourceCulture);
            }
        }

        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }

        public static string CalorieDataMissing {
            get {
                return ResourceManager.GetString("CalorieDataMissing", resourceCulture);
            }
        }

        public static string CaloriesOver {
            get {
                return ResourceManager.GetString("CaloriesOver", resourceCulture);
            }
        }

        public static string CameraNotAvailable {
            get {
                return ResourceManager.GetString("CameraNotAvailable", resourceCulture);
            }
        }

        public static string CaloriesRemaining {
            get {
                return ResourceManager.GetString("CaloriesRemaining", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }

        public static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }

        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        public static string Consumed {
            get {
                return ResourceManager.GetString("Consumed", resourceCulture);
            }
        }

        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }

        public static string CurrentWeight {
            get {
                return ResourceManager.GetString("CurrentWeight", resourceCulture);
            }
        }

        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }

        public static string Days30 {
            get {
                return ResourceManager.GetString("Days30", resourceCulture);
            }
        }

        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }

        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }

        public static string DisclaimerFull {
            get {
                return ResourceManager.GetString("DisclaimerFull", resourceCulture);
            }
        }

        public static string DisclaimerTitle {
            get {
                return ResourceManager.GetString("DisclaimerTitle", resourceCulture);
            }
        }

        public static string EatenToday {
            get {
                return ResourceManager.GetString("EatenToday", resourceCulture);
            }
        }

        public static string EmptyNoEntries {
            get {
                return ResourceManager.GetString("EmptyNoEntries", resourceCulture);
            }
        }

        public static string EmptyNoEntriesDesc {
            get {
                return ResourceManager.GetString("EmptyNoEntriesDesc", resourceCulture);
            }
        }

        public static string EmptyNoFavorites {
            get {
                return ResourceManager.GetString("EmptyNoFavorites", resourceCulture);
            }
        }

        public static string EmptyNoFavoritesDesc {
            get {
                return ResourceManager.GetString("EmptyNoFavoritesDesc", resourceCulture);
            }
        }

        public static string EmptyNoResults {
            get {
                return ResourceManager.GetString("EmptyNoResults", resourceCulture);
            }
        }

        public static string EmptyNoResultsDesc {
            get {
                return ResourceManager.GetString("EmptyNoResultsDesc", resourceCulture);
            }
        }

        public static string EntryDeletedOn {
            get {
                return ResourceManager.GetString("EntryDeletedOn", resourceCulture);
            }
        }

        public static string EnterBarcodeManually {
            get {
                return ResourceManager.GetString("EnterBarcodeManually", resourceCulture);
            }
        }

        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string ErrorSavingData {
            get {
                return ResourceManager.GetString("ErrorSavingData", resourceCulture);
            }
        }

        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }

        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }

        public static string FeedbackButton {
            get {
                return ResourceManager.GetString("FeedbackButton", resourceCulture);
            }
        }

        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }

        public static string FoodSearch {
            get {
                return ResourceManager.GetString("FoodSearch", resourceCulture);
            }
        }

        public static string FoodSearchDesc {
            get {
                return ResourceManager.GetString("FoodSearchDesc", resourceCulture);
            }
        }

        public static string FoodSearchPlaceholder {
            get {
                return ResourceManager.GetString("FoodSearchPlaceholder", resourceCulture);
            }
        }

        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        public static string Glasses {
            get {
                return ResourceManager.GetString("Glasses", resourceCulture);
            }
        }

        public static string GoalLabel {
            get {
                return ResourceManager.GetString("GoalLabel", resourceCulture);
            }
        }

        public static string GoalReached {
            get {
                return ResourceManager.GetString("GoalReached", resourceCulture);
            }
        }

        public static string HealthyBmiRange {
            get {
                return ResourceManager.GetString("HealthyBmiRange", resourceCulture);
            }
        }

        public static string HealthyBodyFatFemale {
            get {
                return ResourceManager.GetString("HealthyBodyFatFemale", resourceCulture);
            }
        }

        public static string HealthyBodyFatMale {
            get {
                return ResourceManager.GetString("HealthyBodyFatMale", resourceCulture);
            }
        }

        public static string HealthyRange {
            get {
                return ResourceManager.GetString("HealthyRange", resourceCulture);
            }
        }

        public static string HeatWater {
            get {
                return ResourceManager.GetString("HeatWater", resourceCulture);
            }
        }

        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }

        public static string HighCalorieWarning {
            get {
                return ResourceManager.GetString("HighCalorieWarning", resourceCulture);
            }
        }

        public static string Hip {
            get {
                return ResourceManager.GetString("Hip", resourceCulture);
            }
        }

        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }

        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }

        public static string HotWeather {
            get {
                return ResourceManager.GetString("HotWeather", resourceCulture);
            }
        }

        public static string IdealWeight {
            get {
                return ResourceManager.GetString("IdealWeight", resourceCulture);
            }
        }

        public static string InvalidValueEntered {
            get {
                return ResourceManager.GetString("InvalidValueEntered", resourceCulture);
            }
        }

        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }

        public static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }

        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }

        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }

        public static string Macronutrients {
            get {
                return ResourceManager.GetString("Macronutrients", resourceCulture);
            }
        }

        public static string Macros {
            get {
                return ResourceManager.GetString("Macros", resourceCulture);
            }
        }

        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }

        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }

        public static string MealType {
            get {
                return ResourceManager.GetString("MealType", resourceCulture);
            }
        }

        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }

        public static string MyCalculators {
            get {
                return ResourceManager.GetString("MyCalculators", resourceCulture);
            }
        }

        public static string MyProgress {
            get {
                return ResourceManager.GetString("MyProgress", resourceCulture);
            }
        }

        public static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }

        public static string NoEntriesYet {
            get {
                return ResourceManager.GetString("NoEntriesYet", resourceCulture);
            }
        }

        public static string NoFoodEntries {
            get {
                return ResourceManager.GetString("NoFoodEntries", resourceCulture);
            }
        }

        public static string NoMealsYet {
            get {
                return ResourceManager.GetString("NoMealsYet", resourceCulture);
            }
        }

        public static string NoteOptional {
            get {
                return ResourceManager.GetString("NoteOptional", resourceCulture);
            }
        }

        public static string NotePlaceholder {
            get {
                return ResourceManager.GetString("NotePlaceholder", resourceCulture);
            }
        }

        public static string NutritionDataIncomplete {
            get {
                return ResourceManager.GetString("NutritionDataIncomplete", resourceCulture);
            }
        }

        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }

        public static string Per100g {
            get {
                return ResourceManager.GetString("Per100g", resourceCulture);
            }
        }

        public static string PortionAmount {
            get {
                return ResourceManager.GetString("PortionAmount", resourceCulture);
            }
        }

        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }

        public static string PremiumBenefits {
            get {
                return ResourceManager.GetString("PremiumBenefits", resourceCulture);
            }
        }

        public static string PremiumBenefitsTitle {
            get {
                return ResourceManager.GetString("PremiumBenefitsTitle", resourceCulture);
            }
        }

        public static string PremiumDescription {
            get {
                return ResourceManager.GetString("PremiumDescription", resourceCulture);
            }
        }

        public static string ProductFound {
            get {
                return ResourceManager.GetString("ProductFound", resourceCulture);
            }
        }

        public static string ProductFoundIncomplete {
            get {
                return ResourceManager.GetString("ProductFoundIncomplete", resourceCulture);
            }
        }

        public static string ProductFoundSomeDataMissing {
            get {
                return ResourceManager.GetString("ProductFoundSomeDataMissing", resourceCulture);
            }
        }

        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }

        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }

        public static string ProgressDesc {
            get {
                return ResourceManager.GetString("ProgressDesc", resourceCulture);
            }
        }

        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }

        public static string PurchasePremium {
            get {
                return ResourceManager.GetString("PurchasePremium", resourceCulture);
            }
        }

        public static string QuickAdd {
            get {
                return ResourceManager.GetString("QuickAdd", resourceCulture);
            }
        }

        public static string QuickAddCalories {
            get {
                return ResourceManager.GetString("QuickAddCalories", resourceCulture);
            }
        }

        public static string QuickAddCaloriesHint {
            get {
                return ResourceManager.GetString("QuickAddCaloriesHint", resourceCulture);
            }
        }

        public static string QuickAddFoodName {
            get {
                return ResourceManager.GetString("QuickAddFoodName", resourceCulture);
            }
        }

        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }

        public static string RemoveAdsDesc {
            get {
                return ResourceManager.GetString("RemoveAdsDesc", resourceCulture);
            }
        }

        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }

        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        public static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }

        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }

        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string SaveToTracking {
            get {
                return ResourceManager.GetString("SaveToTracking", resourceCulture);
            }
        }

        public static string SaveWaterGoal {
            get {
                return ResourceManager.GetString("SaveWaterGoal", resourceCulture);
            }
        }

        public static string ScanBarcode {
            get {
                return ResourceManager.GetString("ScanBarcode", resourceCulture);
            }
        }

        public static string ScanAgain {
            get {
                return ResourceManager.GetString("ScanAgain", resourceCulture);
            }
        }

        public static string SearchBarcodeButton {
            get {
                return ResourceManager.GetString("SearchBarcodeButton", resourceCulture);
            }
        }

        public static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }

        public static string SearchFood {
            get {
                return ResourceManager.GetString("SearchFood", resourceCulture);
            }
        }

        public static string SearchFoodPlaceholder {
            get {
                return ResourceManager.GetString("SearchFoodPlaceholder", resourceCulture);
            }
        }

        public static string SearchingBarcode {
            get {
                return ResourceManager.GetString("SearchingBarcode", resourceCulture);
            }
        }

        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }

        public static string SetAsCalorieGoal {
            get {
                return ResourceManager.GetString("SetAsCalorieGoal", resourceCulture);
            }
        }

        public static string SetCalorieGoal {
            get {
                return ResourceManager.GetString("SetCalorieGoal", resourceCulture);
            }
        }

        public static string SettingsAboutApp {
            get {
                return ResourceManager.GetString("SettingsAboutApp", resourceCulture);
            }
        }

        public static string SettingsChooseDesign {
            get {
                return ResourceManager.GetString("SettingsChooseDesign", resourceCulture);
            }
        }

        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }

        public static string SetWaterGoal {
            get {
                return ResourceManager.GetString("SetWaterGoal", resourceCulture);
            }
        }

        public static string Snack {
            get {
                return ResourceManager.GetString("Snack", resourceCulture);
            }
        }

        public static string TabBody {
            get {
                return ResourceManager.GetString("TabBody", resourceCulture);
            }
        }

        public static string TabCalories {
            get {
                return ResourceManager.GetString("TabCalories", resourceCulture);
            }
        }

        public static string TabFood {
            get {
                return ResourceManager.GetString("TabFood", resourceCulture);
            }
        }

        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }

        public static string TabProgress {
            get {
                return ResourceManager.GetString("TabProgress", resourceCulture);
            }
        }

        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }

        public static string TabWater {
            get {
                return ResourceManager.GetString("TabWater", resourceCulture);
            }
        }

        public static string TabWeight {
            get {
                return ResourceManager.GetString("TabWeight", resourceCulture);
            }
        }

        public static string TapToAdd {
            get {
                return ResourceManager.GetString("TapToAdd", resourceCulture);
            }
        }

        public static string TapToChange {
            get {
                return ResourceManager.GetString("TapToChange", resourceCulture);
            }
        }

        public static string TapToSearch {
            get {
                return ResourceManager.GetString("TapToSearch", resourceCulture);
            }
        }

        public static string Tdee {
            get {
                return ResourceManager.GetString("Tdee", resourceCulture);
            }
        }

        public static string ThemeClassic {
            get {
                return ResourceManager.GetString("ThemeClassic", resourceCulture);
            }
        }

        public static string ThemeClassicDesc {
            get {
                return ResourceManager.GetString("ThemeClassicDesc", resourceCulture);
            }
        }

        public static string ThemeGlassDark {
            get {
                return ResourceManager.GetString("ThemeGlassDark", resourceCulture);
            }
        }

        public static string ThemeGlassDarkDesc {
            get {
                return ResourceManager.GetString("ThemeGlassDarkDesc", resourceCulture);
            }
        }

        public static string ThemeSoftLight {
            get {
                return ResourceManager.GetString("ThemeSoftLight", resourceCulture);
            }
        }

        public static string ThemeSoftLightDesc {
            get {
                return ResourceManager.GetString("ThemeSoftLightDesc", resourceCulture);
            }
        }

        public static string ThemeVivid {
            get {
                return ResourceManager.GetString("ThemeVivid", resourceCulture);
            }
        }

        public static string ThemeVividDesc {
            get {
                return ResourceManager.GetString("ThemeVividDesc", resourceCulture);
            }
        }

        public static string TodayDashboard {
            get {
                return ResourceManager.GetString("TodayDashboard", resourceCulture);
            }
        }

        public static string TodayLog {
            get {
                return ResourceManager.GetString("TodayLog", resourceCulture);
            }
        }

        public static string TodayMeals {
            get {
                return ResourceManager.GetString("TodayMeals", resourceCulture);
            }
        }

        public static string TotalWater {
            get {
                return ResourceManager.GetString("TotalWater", resourceCulture);
            }
        }

        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }

        public static string TrackingAddEntry {
            get {
                return ResourceManager.GetString("TrackingAddEntry", resourceCulture);
            }
        }

        public static string TrackingCalories {
            get {
                return ResourceManager.GetString("TrackingCalories", resourceCulture);
            }
        }

        public static string TrackingDate {
            get {
                return ResourceManager.GetString("TrackingDate", resourceCulture);
            }
        }

        public static string TrackingDesc {
            get {
                return ResourceManager.GetString("TrackingDesc", resourceCulture);
            }
        }

        public static string TrackingDescription {
            get {
                return ResourceManager.GetString("TrackingDescription", resourceCulture);
            }
        }

        public static string TrackingNoEntries {
            get {
                return ResourceManager.GetString("TrackingNoEntries", resourceCulture);
            }
        }

        public static string TrackingNote {
            get {
                return ResourceManager.GetString("TrackingNote", resourceCulture);
            }
        }

        public static string TrackingNotePlaceholder {
            get {
                return ResourceManager.GetString("TrackingNotePlaceholder", resourceCulture);
            }
        }

        public static string TrackingTitle {
            get {
                return ResourceManager.GetString("TrackingTitle", resourceCulture);
            }
        }

        public static string TrackingWater {
            get {
                return ResourceManager.GetString("TrackingWater", resourceCulture);
            }
        }

        public static string TrackingWeight {
            get {
                return ResourceManager.GetString("TrackingWeight", resourceCulture);
            }
        }

        public static string Trend {
            get {
                return ResourceManager.GetString("Trend", resourceCulture);
            }
        }

        public static string TrialInfo {
            get {
                return ResourceManager.GetString("TrialInfo", resourceCulture);
            }
        }

        public static string TrialOfferBuyNow {
            get {
                return ResourceManager.GetString("TrialOfferBuyNow", resourceCulture);
            }
        }

        public static string TrialOfferStart {
            get {
                return ResourceManager.GetString("TrialOfferStart", resourceCulture);
            }
        }

        public static string TrialOfferTitle {
            get {
                return ResourceManager.GetString("TrialOfferTitle", resourceCulture);
            }
        }

        public static string TrialStartedMessage {
            get {
                return ResourceManager.GetString("TrialStartedMessage", resourceCulture);
            }
        }

        public static string TrialStartedTitle {
            get {
                return ResourceManager.GetString("TrialStartedTitle", resourceCulture);
            }
        }

        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }

        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }

        public static string ViewProgress {
            get {
                return ResourceManager.GetString("ViewProgress", resourceCulture);
            }
        }

        public static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }

        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        public static string WaterGoal {
            get {
                return ResourceManager.GetString("WaterGoal", resourceCulture);
            }
        }

        public static string WaterGoalMl {
            get {
                return ResourceManager.GetString("WaterGoalMl", resourceCulture);
            }
        }

        public static string WaterStats {
            get {
                return ResourceManager.GetString("WaterStats", resourceCulture);
            }
        }

        public static string WaterToday {
            get {
                return ResourceManager.GetString("WaterToday", resourceCulture);
            }
        }

        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }

        public static string WeightEntries {
            get {
                return ResourceManager.GetString("WeightEntries", resourceCulture);
            }
        }

        public static string WeightGain {
            get {
                return ResourceManager.GetString("WeightGain", resourceCulture);
            }
        }

        public static string WeightLoss {
            get {
                return ResourceManager.GetString("WeightLoss", resourceCulture);
            }
        }

        public static string WeightStats30Days {
            get {
                return ResourceManager.GetString("WeightStats30Days", resourceCulture);
            }
        }

        public static string WeightValue {
            get {
                return ResourceManager.GetString("WeightValue", resourceCulture);
            }
        }

        public static string WaterRemaining {
            get {
                return ResourceManager.GetString("WaterRemaining", resourceCulture);
            }
        }

        public static string UnknownProduct {
            get {
                return ResourceManager.GetString("UnknownProduct", resourceCulture);
            }
        }

        public static string UseProduct {
            get {
                return ResourceManager.GetString("UseProduct", resourceCulture);
            }
        }

        public static string RemoveAds {
            get {
                return ResourceManager.GetString("RemoveAds", resourceCulture);
            }
        }

        public static string PremiumPrice {
            get {
                return ResourceManager.GetString("PremiumPrice", resourceCulture);
            }
        }

        public static string GetPremium {
            get {
                return ResourceManager.GetString("GetPremium", resourceCulture);
            }
        }

        public static string SectionCalculators {
            get {
                return ResourceManager.GetString("SectionCalculators", resourceCulture);
            }
        }

        public static string RemainingScans {
            get {
                return ResourceManager.GetString("RemainingScans", resourceCulture);
            }
        }

        public static string ScanLimitTitle {
            get {
                return ResourceManager.GetString("ScanLimitTitle", resourceCulture);
            }
        }

        public static string ScanLimitMessage {
            get {
                return ResourceManager.GetString("ScanLimitMessage", resourceCulture);
            }
        }

        public static string WatchAdForScans {
            get {
                return ResourceManager.GetString("WatchAdForScans", resourceCulture);
            }
        }

        public static string WeeklyAnalysis {
            get {
                return ResourceManager.GetString("WeeklyAnalysis", resourceCulture);
            }
        }

        public static string WeeklyAnalysisDesc {
            get {
                return ResourceManager.GetString("WeeklyAnalysisDesc", resourceCulture);
            }
        }

        public static string AvgWeight {
            get {
                return ResourceManager.GetString("AvgWeight", resourceCulture);
            }
        }

        public static string AvgCalories {
            get {
                return ResourceManager.GetString("AvgCalories", resourceCulture);
            }
        }

        public static string AvgWater {
            get {
                return ResourceManager.GetString("AvgWater", resourceCulture);
            }
        }

        public static string WeightTrend {
            get {
                return ResourceManager.GetString("WeightTrend", resourceCulture);
            }
        }

        public static string CalorieTarget {
            get {
                return ResourceManager.GetString("CalorieTarget", resourceCulture);
            }
        }

        public static string ExportTracking {
            get {
                return ResourceManager.GetString("ExportTracking", resourceCulture);
            }
        }

        public static string ExportTrackingDesc {
            get {
                return ResourceManager.GetString("ExportTrackingDesc", resourceCulture);
            }
        }

        public static string ExtendedFoodDb {
            get {
                return ResourceManager.GetString("ExtendedFoodDb", resourceCulture);
            }
        }

        public static string ExtendedFoodDbDesc {
            get {
                return ResourceManager.GetString("ExtendedFoodDbDesc", resourceCulture);
            }
        }

        public static string AdVideoNotAvailableTitle {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableTitle", resourceCulture);
            }
        }

        public static string AdVideoNotAvailableMessage {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableMessage", resourceCulture);
            }
        }

        public static string AlertInvalidInput {
            get {
                return ResourceManager.GetString("AlertInvalidInput", resourceCulture);
            }
        }

        public static string AlertBodyFatMeasurement {
            get {
                return ResourceManager.GetString("AlertBodyFatMeasurement", resourceCulture);
            }
        }

        public static string BarcodeScanHint {
            get {
                return ResourceManager.GetString("BarcodeScanHint", resourceCulture);
            }
        }

        public static string PressBackAgainToExit {
            get {
                return ResourceManager.GetString("PressBackAgainToExit", resourceCulture);
            }
        }

        public static string WeightGoalLabel {
            get {
                return ResourceManager.GetString("WeightGoalLabel", resourceCulture);
            }
        }

        public static string SetWeightGoal {
            get {
                return ResourceManager.GetString("SetWeightGoal", resourceCulture);
            }
        }

        public static string WeightGoalKg {
            get {
                return ResourceManager.GetString("WeightGoalKg", resourceCulture);
            }
        }

        public static string WeightRemaining {
            get {
                return ResourceManager.GetString("WeightRemaining", resourceCulture);
            }
        }

        public static string EmptyWeightHint {
            get {
                return ResourceManager.GetString("EmptyWeightHint", resourceCulture);
            }
        }

        public static string EmptyCaloriesHint {
            get {
                return ResourceManager.GetString("EmptyCaloriesHint", resourceCulture);
            }
        }

        public static string EmptyWaterHint {
            get {
                return ResourceManager.GetString("EmptyWaterHint", resourceCulture);
            }
        }

        public static string EmptyBmiHint {
            get {
                return ResourceManager.GetString("EmptyBmiHint", resourceCulture);
            }
        }

        public static string EmptyBodyFatHint {
            get {
                return ResourceManager.GetString("EmptyBodyFatHint", resourceCulture);
            }
        }

        public static string MealSubtotal {
            get {
                return ResourceManager.GetString("MealSubtotal", resourceCulture);
            }
        }

        public static string RecentFoods {
            get {
                return ResourceManager.GetString("RecentFoods", resourceCulture);
            }
        }

        public static string CopyYesterday {
            get {
                return ResourceManager.GetString("CopyYesterday", resourceCulture);
            }
        }

        public static string MealsCopied {
            get {
                return ResourceManager.GetString("MealsCopied", resourceCulture);
            }
        }

        public static string NoMealsYesterday {
            get {
                return ResourceManager.GetString("NoMealsYesterday", resourceCulture);
            }
        }

        public static string Days7 {
            get {
                return ResourceManager.GetString("Days7", resourceCulture);
            }
        }

        public static string Days90 {
            get {
                return ResourceManager.GetString("Days90", resourceCulture);
            }
        }

        public static string GreetingMorning {
            get {
                return ResourceManager.GetString("GreetingMorning", resourceCulture);
            }
        }

        public static string GreetingAfternoon {
            get {
                return ResourceManager.GetString("GreetingAfternoon", resourceCulture);
            }
        }

        public static string GreetingEvening {
            get {
                return ResourceManager.GetString("GreetingEvening", resourceCulture);
            }
        }

        public static string PortionDefault {
            get {
                return ResourceManager.GetString("PortionDefault", resourceCulture);
            }
        }

        public static string WeeklyCalories {
            get {
                return ResourceManager.GetString("WeeklyCalories", resourceCulture);
            }
        }

        public static string StreakIncreased {
            get {
                return ResourceManager.GetString("StreakIncreased", resourceCulture);
            }
        }

        public static string QuickAddWeight {
            get {
                return ResourceManager.GetString("QuickAddWeight", resourceCulture);
            }
        }
    }
}
