//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandwerkerRechner.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandwerkerRechner.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Material calculator for craftsmen and DIY ähnelt.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CraftsmanCalc ähnelt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area (m²) ähnelt.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area to Calculate ähnelt.
        /// </summary>
        internal static string AreaToCalculate {
            get {
                return ResourceManager.GetString("AreaToCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Board Dimensions ähnelt.
        /// </summary>
        internal static string BoardDimensions {
            get {
                return ResourceManager.GetString("BoardDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Board length (m) ähnelt.
        /// </summary>
        internal static string BoardLength {
            get {
                return ResourceManager.GetString("BoardLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boards needed ähnelt.
        /// </summary>
        internal static string BoardsNeeded {
            get {
                return ResourceManager.GetString("BoardsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With waste ähnelt.
        /// </summary>
        internal static string BoardsWithWaste {
            get {
                return ResourceManager.GetString("BoardsWithWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Board width (cm) ähnelt.
        /// </summary>
        internal static string BoardWidth {
            get {
                return ResourceManager.GetString("BoardWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flooring ähnelt.
        /// </summary>
        internal static string CalcFlooring {
            get {
                return ResourceManager.GetString("CalcFlooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paint ähnelt.
        /// </summary>
        internal static string CalcPaint {
            get {
                return ResourceManager.GetString("CalcPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tiles ähnelt.
        /// </summary>
        internal static string CalcTiles {
            get {
                return ResourceManager.GetString("CalcTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate ähnelt.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wallpaper ähnelt.
        /// </summary>
        internal static string CalcWallpaper {
            get {
                return ResourceManager.GetString("CalcWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drywall ähnelt.
        /// </summary>
        internal static string CategoryDrywall {
            get {
                return ResourceManager.GetString("CategoryDrywall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Electrical ähnelt.
        /// </summary>
        internal static string CategoryElectrical {
            get {
                return ResourceManager.GetString("CategoryElectrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Floor &amp; Wall ähnelt.
        /// </summary>
        internal static string CategoryFloorWall {
            get {
                return ResourceManager.GetString("CategoryFloorWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Garden ähnelt.
        /// </summary>
        internal static string CategoryGarden {
            get {
                return ResourceManager.GetString("CategoryGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metal ähnelt.
        /// </summary>
        internal static string CategoryMetal {
            get {
                return ResourceManager.GetString("CategoryMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roof &amp; Solar ähnelt.
        /// </summary>
        internal static string CategoryRoofSolar {
            get {
                return ResourceManager.GetString("CategoryRoofSolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coats ähnelt.
        /// </summary>
        internal static string Coats {
            get {
                return ResourceManager.GetString("Coats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coverage (m²/L) ähnelt.
        /// </summary>
        internal static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send Feedback ähnelt.
        /// </summary>
        internal static string FeedbackButton {
            get {
                return ResourceManager.GetString("FeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liters needed ähnelt.
        /// </summary>
        internal static string LitersNeeded {
            get {
                return ResourceManager.GetString("LitersNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paint Properties ähnelt.
        /// </summary>
        internal static string PaintProperties {
            get {
                return ResourceManager.GetString("PaintProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pattern repeat (cm) ähnelt.
        /// </summary>
        internal static string PatternRepeat {
            get {
                return ResourceManager.GetString("PatternRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium ähnelt.
        /// </summary>
        internal static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock all calculators and remove ads ähnelt.
        /// </summary>
        internal static string PremiumDescription {
            get {
                return ResourceManager.GetString("PremiumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium required ähnelt.
        /// </summary>
        internal static string PremiumRequired {
            get {
                return ResourceManager.GetString("PremiumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase Premium ähnelt.
        /// </summary>
        internal static string PurchasePremium {
            get {
                return ResourceManager.GetString("PurchasePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore Purchases ähnelt.
        /// </summary>
        internal static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll Dimensions ähnelt.
        /// </summary>
        internal static string RollDimensions {
            get {
                return ResourceManager.GetString("RollDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll length (m) ähnelt.
        /// </summary>
        internal static string RollLength {
            get {
                return ResourceManager.GetString("RollLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolls needed ähnelt.
        /// </summary>
        internal static string RollsNeeded {
            get {
                return ResourceManager.GetString("RollsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll width (cm) ähnelt.
        /// </summary>
        internal static string RollWidth {
            get {
                return ResourceManager.GetString("RollWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room Dimensions ähnelt.
        /// </summary>
        internal static string RoomDimensions {
            get {
                return ResourceManager.GetString("RoomDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room height (m) ähnelt.
        /// </summary>
        internal static string RoomHeight {
            get {
                return ResourceManager.GetString("RoomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room length (m) ähnelt.
        /// </summary>
        internal static string RoomLength {
            get {
                return ResourceManager.GetString("RoomLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room width (m) ähnelt.
        /// </summary>
        internal static string RoomWidth {
            get {
                return ResourceManager.GetString("RoomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About App ähnelt.
        /// </summary>
        internal static string SettingsAboutApp {
            get {
                return ResourceManager.GetString("SettingsAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string SettingsBack {
            get {
                return ResourceManager.GetString("SettingsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Design ähnelt.
        /// </summary>
        internal static string SettingsChooseDesign {
            get {
                return ResourceManager.GetString("SettingsChooseDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classic ähnelt.
        /// </summary>
        internal static string ThemeClassic {
            get {
                return ResourceManager.GetString("ThemeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean &amp; Clear ähnelt.
        /// </summary>
        internal static string ThemeClassicDesc {
            get {
                return ResourceManager.GetString("ThemeClassicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glass Dark ähnelt.
        /// </summary>
        internal static string ThemeGlassDark {
            get {
                return ResourceManager.GetString("ThemeGlassDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elegant &amp; Dark ähnelt.
        /// </summary>
        internal static string ThemeGlassDarkDesc {
            get {
                return ResourceManager.GetString("ThemeGlassDarkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soft Light ähnelt.
        /// </summary>
        internal static string ThemeSoftLight {
            get {
                return ResourceManager.GetString("ThemeSoftLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soft &amp; Light ähnelt.
        /// </summary>
        internal static string ThemeSoftLightDesc {
            get {
                return ResourceManager.GetString("ThemeSoftLightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vivid ähnelt.
        /// </summary>
        internal static string ThemeVivid {
            get {
                return ResourceManager.GetString("ThemeVivid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modern &amp; Vibrant ähnelt.
        /// </summary>
        internal static string ThemeVividDesc {
            get {
                return ResourceManager.GetString("ThemeVividDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tile Dimensions ähnelt.
        /// </summary>
        internal static string TileDimensions {
            get {
                return ResourceManager.GetString("TileDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tile length (cm) ähnelt.
        /// </summary>
        internal static string TileLength {
            get {
                return ResourceManager.GetString("TileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tiles needed ähnelt.
        /// </summary>
        internal static string TilesNeeded {
            get {
                return ResourceManager.GetString("TilesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With waste ähnelt.
        /// </summary>
        internal static string TilesWithWaste {
            get {
                return ResourceManager.GetString("TilesWithWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tile width (cm) ähnelt.
        /// </summary>
        internal static string TileWidth {
            get {
                return ResourceManager.GetString("TileWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total area (with coats) ähnelt.
        /// </summary>
        internal static string TotalArea {
            get {
                return ResourceManager.GetString("TotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wall area ähnelt.
        /// </summary>
        internal static string WallArea {
            get {
                return ResourceManager.GetString("WallArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wall length (m) ähnelt.
        /// </summary>
        internal static string WallLength {
            get {
                return ResourceManager.GetString("WallLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waste (%) ähnelt.
        /// </summary>
        internal static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }

        internal static string TrialOfferTitle {
            get {
                return ResourceManager.GetString("TrialOfferTitle", resourceCulture);
            }
        }

        internal static string TrialOfferStart {
            get {
                return ResourceManager.GetString("TrialOfferStart", resourceCulture);
            }
        }

        internal static string TrialOfferBuyNow {
            get {
                return ResourceManager.GetString("TrialOfferBuyNow", resourceCulture);
            }
        }

        internal static string TrialStartedTitle {
            get {
                return ResourceManager.GetString("TrialStartedTitle", resourceCulture);
            }
        }

        internal static string TrialStartedMessage {
            get {
                return ResourceManager.GetString("TrialStartedMessage", resourceCulture);
            }
        }

        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        internal static string HistoryThreadSize {
            get {
                return ResourceManager.GetString("HistoryThreadSize", resourceCulture);
            }
        }

        internal static string CableCostLabel {
            get {
                return ResourceManager.GetString("CableCostLabel", resourceCulture);
            }
        }

        internal static string HistoryHoursPerDay {
            get {
                return ResourceManager.GetString("HistoryHoursPerDay", resourceCulture);
            }
        }

        internal static string HistorySoilDepth {
            get {
                return ResourceManager.GetString("HistorySoilDepth", resourceCulture);
            }
        }

        internal static string HistoryYears {
            get {
                return ResourceManager.GetString("HistoryYears", resourceCulture);
            }
        }

        internal static string HistoryRoofPitch {
            get {
                return ResourceManager.GetString("HistoryRoofPitch", resourceCulture);
            }
        }

        internal static string HistoryRoofArea {
            get {
                return ResourceManager.GetString("HistoryRoofArea", resourceCulture);
            }
        }

        internal static string HistoryDoubleLayered {
            get {
                return ResourceManager.GetString("HistoryDoubleLayered", resourceCulture);
            }
        }

        internal static string HistoryWallHeight {
            get {
                return ResourceManager.GetString("HistoryWallHeight", resourceCulture);
            }
        }

        internal static string HistoryPaintCoats {
            get {
                return ResourceManager.GetString("HistoryPaintCoats", resourceCulture);
            }
        }

        internal static string SectionFloorWall {
            get {
                return ResourceManager.GetString("SectionFloorWall", resourceCulture);
            }
        }

        internal static string SectionPremiumTools {
            get {
                return ResourceManager.GetString("SectionPremiumTools", resourceCulture);
            }
        }

        internal static string CalculatorCount {
            get {
                return ResourceManager.GetString("CalculatorCount", resourceCulture);
            }
        }

        internal static string GetPremium {
            get {
                return ResourceManager.GetString("GetPremium", resourceCulture);
            }
        }

        internal static string PremiumPrice {
            get {
                return ResourceManager.GetString("PremiumPrice", resourceCulture);
            }
        }

        internal static string MoreCategories {
            get {
                return ResourceManager.GetString("MoreCategories", resourceCulture);
            }
        }

        // Rewarded Ads
        internal static string PremiumCalculatorsLocked {
            get {
                return ResourceManager.GetString("PremiumCalculatorsLocked", resourceCulture);
            }
        }

        internal static string WatchVideoFor30Min {
            get {
                return ResourceManager.GetString("WatchVideoFor30Min", resourceCulture);
            }
        }

        internal static string AccessGranted {
            get {
                return ResourceManager.GetString("AccessGranted", resourceCulture);
            }
        }

        internal static string AccessExpiresIn {
            get {
                return ResourceManager.GetString("AccessExpiresIn", resourceCulture);
            }
        }

        internal static string TemporaryAccessActive {
            get {
                return ResourceManager.GetString("TemporaryAccessActive", resourceCulture);
            }
        }

        internal static string VideoFor30Min {
            get {
                return ResourceManager.GetString("VideoFor30Min", resourceCulture);
            }
        }

        internal static string ExtendedHistoryTitle {
            get {
                return ResourceManager.GetString("ExtendedHistoryTitle", resourceCulture);
            }
        }

        internal static string ExtendedHistoryDesc {
            get {
                return ResourceManager.GetString("ExtendedHistoryDesc", resourceCulture);
            }
        }

        internal static string ExportMaterialList {
            get {
                return ResourceManager.GetString("ExportMaterialList", resourceCulture);
            }
        }

        internal static string ExportMaterialDesc {
            get {
                return ResourceManager.GetString("ExportMaterialDesc", resourceCulture);
            }
        }

        internal static string ExportProject {
            get {
                return ResourceManager.GetString("ExportProject", resourceCulture);
            }
        }

        internal static string ExportProjectDesc {
            get {
                return ResourceManager.GetString("ExportProjectDesc", resourceCulture);
            }
        }

        internal static string MaterialListPdf {
            get {
                return ResourceManager.GetString("MaterialListPdf", resourceCulture);
            }
        }

        internal static string ProjectReport {
            get {
                return ResourceManager.GetString("ProjectReport", resourceCulture);
            }
        }
    }
}
