using FitnessRechner.Models;

namespace FitnessRechner.Services;

/// <summary>
/// Lokale Datenbank mit Nährwertinformationen für gängige Lebensmittel.
/// IDs sind deterministisch (Name-basiert) und stabil über App-Neustarts.
/// </summary>
public static class FoodDatabase
{
    public static readonly List<FoodItem> Foods;

    static FoodDatabase()
    {
        Foods = CreateFoods();

        // Deterministische IDs statt zufällige GUIDs (stabil über App-Neustarts)
        foreach (var food in Foods)
        {
            food.Id = $"db_{food.Name.ToLowerInvariant().Replace(' ', '_')}";
        }
    }

    private static List<FoodItem> CreateFoods() =>
    [
        // === OBST ===
        new() { Name = "Apfel", Aliases = ["Apple", "Äpfel"], Category = FoodCategory.Fruit,
            CaloriesPer100g = 52, ProteinPer100g = 0.3, CarbsPer100g = 14, FatPer100g = 0.2, FiberPer100g = 2.4,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 180 },
        new() { Name = "Banane", Aliases = ["Banana"], Category = FoodCategory.Fruit,
            CaloriesPer100g = 89, ProteinPer100g = 1.1, CarbsPer100g = 23, FatPer100g = 0.3, FiberPer100g = 2.6,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 120 },
        new() { Name = "Orange", Aliases = ["Apfelsine"], Category = FoodCategory.Fruit,
            CaloriesPer100g = 47, ProteinPer100g = 0.9, CarbsPer100g = 12, FatPer100g = 0.1, FiberPer100g = 2.4,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 150 },
        new() { Name = "Erdbeeren", Aliases = ["Strawberry", "Strawberries"], Category = FoodCategory.Fruit,
            CaloriesPer100g = 32, ProteinPer100g = 0.7, CarbsPer100g = 8, FatPer100g = 0.3, FiberPer100g = 2,
            DefaultPortion = "Schale", DefaultPortionGrams = 150 },
        new() { Name = "Weintrauben", Aliases = ["Trauben", "Grapes"], Category = FoodCategory.Fruit,
            CaloriesPer100g = 67, ProteinPer100g = 0.6, CarbsPer100g = 17, FatPer100g = 0.4, FiberPer100g = 0.9,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 100 },
        new() { Name = "Wassermelone", Aliases = ["Melone", "Watermelon"], Category = FoodCategory.Fruit,
            CaloriesPer100g = 30, ProteinPer100g = 0.6, CarbsPer100g = 8, FatPer100g = 0.2, FiberPer100g = 0.4,
            DefaultPortion = "Stück", DefaultPortionGrams = 200 },
        new() { Name = "Mango", Aliases = [], Category = FoodCategory.Fruit,
            CaloriesPer100g = 60, ProteinPer100g = 0.8, CarbsPer100g = 15, FatPer100g = 0.4, FiberPer100g = 1.6,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 200 },
        new() { Name = "Kiwi", Aliases = [], Category = FoodCategory.Fruit,
            CaloriesPer100g = 61, ProteinPer100g = 1.1, CarbsPer100g = 15, FatPer100g = 0.5, FiberPer100g = 3,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 75 },

        // === GEMÜSE ===
        new() { Name = "Tomate", Aliases = ["Tomaten", "Tomato"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 18, ProteinPer100g = 0.9, CarbsPer100g = 3.9, FatPer100g = 0.2, FiberPer100g = 1.2,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 120 },
        new() { Name = "Gurke", Aliases = ["Cucumber", "Salatgurke"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 12, ProteinPer100g = 0.6, CarbsPer100g = 2, FatPer100g = 0.1, FiberPer100g = 0.5,
            DefaultPortion = "halbe", DefaultPortionGrams = 150 },
        new() { Name = "Karotte", Aliases = ["Möhre", "Carrot", "Mohrrübe"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 41, ProteinPer100g = 0.9, CarbsPer100g = 10, FatPer100g = 0.2, FiberPer100g = 2.8,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 80 },
        new() { Name = "Brokkoli", Aliases = ["Broccoli"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 34, ProteinPer100g = 2.8, CarbsPer100g = 7, FatPer100g = 0.4, FiberPer100g = 2.6,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Paprika", Aliases = ["Bell Pepper", "Gemüsepaprika"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 31, ProteinPer100g = 1, CarbsPer100g = 6, FatPer100g = 0.3, FiberPer100g = 2.1,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 160 },
        new() { Name = "Spinat", Aliases = ["Spinach"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 23, ProteinPer100g = 2.9, CarbsPer100g = 3.6, FatPer100g = 0.4, FiberPer100g = 2.2,
            DefaultPortion = "Portion", DefaultPortionGrams = 100 },
        new() { Name = "Zwiebel", Aliases = ["Onion", "Zwiebeln"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 40, ProteinPer100g = 1.1, CarbsPer100g = 9, FatPer100g = 0.1, FiberPer100g = 1.7,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 100 },
        new() { Name = "Kartoffel", Aliases = ["Potato", "Kartoffeln"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 77, ProteinPer100g = 2, CarbsPer100g = 17, FatPer100g = 0.1, FiberPer100g = 2.2,
            DefaultPortion = "1 mittel", DefaultPortionGrams = 150 },
        new() { Name = "Salat", Aliases = ["Kopfsalat", "Lettuce", "Eisbergsalat"], Category = FoodCategory.Vegetable,
            CaloriesPer100g = 14, ProteinPer100g = 1.2, CarbsPer100g = 2.4, FatPer100g = 0.2, FiberPer100g = 1.3,
            DefaultPortion = "Portion", DefaultPortionGrams = 80 },

        // === FLEISCH ===
        new() { Name = "Hähnchenbrust", Aliases = ["Hühnerbrust", "Chicken Breast", "Huhn"], Category = FoodCategory.Meat,
            CaloriesPer100g = 165, ProteinPer100g = 31, CarbsPer100g = 0, FatPer100g = 3.6, FiberPer100g = 0,
            DefaultPortion = "1 Filet", DefaultPortionGrams = 150 },
        new() { Name = "Rindfleisch", Aliases = ["Beef", "Rind", "Steak"], Category = FoodCategory.Meat,
            CaloriesPer100g = 250, ProteinPer100g = 26, CarbsPer100g = 0, FatPer100g = 15, FiberPer100g = 0,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Schweinefleisch", Aliases = ["Pork", "Schwein", "Schnitzel"], Category = FoodCategory.Meat,
            CaloriesPer100g = 242, ProteinPer100g = 27, CarbsPer100g = 0, FatPer100g = 14, FiberPer100g = 0,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Hackfleisch", Aliases = ["Mince", "Gehacktes", "Hackfleisch gemischt"], Category = FoodCategory.Meat,
            CaloriesPer100g = 212, ProteinPer100g = 18, CarbsPer100g = 0, FatPer100g = 15, FiberPer100g = 0,
            DefaultPortion = "Portion", DefaultPortionGrams = 125 },
        new() { Name = "Schinken", Aliases = ["Ham", "Kochschinken"], Category = FoodCategory.Meat,
            CaloriesPer100g = 145, ProteinPer100g = 21, CarbsPer100g = 1, FatPer100g = 6, FiberPer100g = 0,
            DefaultPortion = "2 Scheiben", DefaultPortionGrams = 40 },
        new() { Name = "Salami", Aliases = [], Category = FoodCategory.Meat,
            CaloriesPer100g = 336, ProteinPer100g = 26, CarbsPer100g = 1, FatPer100g = 25, FiberPer100g = 0,
            DefaultPortion = "5 Scheiben", DefaultPortionGrams = 30 },

        // === FISCH ===
        new() { Name = "Lachs", Aliases = ["Salmon", "Lachsfilet"], Category = FoodCategory.Fish,
            CaloriesPer100g = 208, ProteinPer100g = 20, CarbsPer100g = 0, FatPer100g = 13, FiberPer100g = 0,
            DefaultPortion = "1 Filet", DefaultPortionGrams = 150 },
        new() { Name = "Thunfisch", Aliases = ["Tuna", "Thunfisch Dose"], Category = FoodCategory.Fish,
            CaloriesPer100g = 132, ProteinPer100g = 29, CarbsPer100g = 0, FatPer100g = 1, FiberPer100g = 0,
            DefaultPortion = "1 Dose", DefaultPortionGrams = 150 },
        new() { Name = "Forelle", Aliases = ["Trout"], Category = FoodCategory.Fish,
            CaloriesPer100g = 119, ProteinPer100g = 20, CarbsPer100g = 0, FatPer100g = 4, FiberPer100g = 0,
            DefaultPortion = "1 Filet", DefaultPortionGrams = 150 },
        new() { Name = "Garnelen", Aliases = ["Shrimp", "Prawns", "Krabben"], Category = FoodCategory.Fish,
            CaloriesPer100g = 99, ProteinPer100g = 24, CarbsPer100g = 0, FatPer100g = 0.3, FiberPer100g = 0,
            DefaultPortion = "Portion", DefaultPortionGrams = 100 },

        // === MILCHPRODUKTE ===
        new() { Name = "Milch", Aliases = ["Vollmilch", "Milk"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 64, ProteinPer100g = 3.3, CarbsPer100g = 4.8, FatPer100g = 3.5, FiberPer100g = 0,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 250 },
        new() { Name = "Käse", Aliases = ["Gouda", "Cheese", "Edamer"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 356, ProteinPer100g = 25, CarbsPer100g = 0, FatPer100g = 28, FiberPer100g = 0,
            DefaultPortion = "2 Scheiben", DefaultPortionGrams = 40 },
        new() { Name = "Joghurt", Aliases = ["Yogurt", "Naturjoghurt"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 61, ProteinPer100g = 3.5, CarbsPer100g = 4.7, FatPer100g = 3.3, FiberPer100g = 0,
            DefaultPortion = "1 Becher", DefaultPortionGrams = 150 },
        new() { Name = "Quark", Aliases = ["Magerquark", "Speisequark"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 67, ProteinPer100g = 12, CarbsPer100g = 4, FatPer100g = 0.3, FiberPer100g = 0,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Butter", Aliases = [], Category = FoodCategory.Dairy,
            CaloriesPer100g = 717, ProteinPer100g = 0.9, CarbsPer100g = 0.1, FatPer100g = 81, FiberPer100g = 0,
            DefaultPortion = "1 EL", DefaultPortionGrams = 10 },
        new() { Name = "Ei", Aliases = ["Eier", "Egg", "Hühnerei"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 155, ProteinPer100g = 13, CarbsPer100g = 1.1, FatPer100g = 11, FiberPer100g = 0,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 60 },

        // === GETREIDE/BROT ===
        new() { Name = "Brot", Aliases = ["Vollkornbrot", "Bread", "Mischbrot"], Category = FoodCategory.Grain,
            CaloriesPer100g = 247, ProteinPer100g = 8, CarbsPer100g = 49, FatPer100g = 1.3, FiberPer100g = 4.4,
            DefaultPortion = "1 Scheibe", DefaultPortionGrams = 50 },
        new() { Name = "Brötchen", Aliases = ["Semmel", "Roll", "Weizenbrötchen"], Category = FoodCategory.Grain,
            CaloriesPer100g = 270, ProteinPer100g = 9, CarbsPer100g = 52, FatPer100g = 2, FiberPer100g = 2.7,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 50 },
        new() { Name = "Reis", Aliases = ["Rice", "Basmati"], Category = FoodCategory.Grain,
            CaloriesPer100g = 130, ProteinPer100g = 2.7, CarbsPer100g = 28, FatPer100g = 0.3, FiberPer100g = 0.4,
            DefaultPortion = "Portion gekocht", DefaultPortionGrams = 150 },
        new() { Name = "Nudeln", Aliases = ["Pasta", "Spaghetti", "Penne"], Category = FoodCategory.Grain,
            CaloriesPer100g = 131, ProteinPer100g = 5, CarbsPer100g = 25, FatPer100g = 1.1, FiberPer100g = 1.8,
            DefaultPortion = "Portion gekocht", DefaultPortionGrams = 180 },
        new() { Name = "Haferflocken", Aliases = ["Oats", "Oatmeal", "Hafer"], Category = FoodCategory.Grain,
            CaloriesPer100g = 372, ProteinPer100g = 13, CarbsPer100g = 59, FatPer100g = 7, FiberPer100g = 10,
            DefaultPortion = "Portion", DefaultPortionGrams = 50 },
        new() { Name = "Müsli", Aliases = ["Muesli", "Cerealien", "Hafermüsli"], Category = FoodCategory.Grain,
            CaloriesPer100g = 367, ProteinPer100g = 9, CarbsPer100g = 66, FatPer100g = 6, FiberPer100g = 7,
            DefaultPortion = "Portion", DefaultPortionGrams = 50 },

        // === GETRÄNKE ===
        new() { Name = "Orangensaft", Aliases = ["Orange Juice", "O-Saft"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 45, ProteinPer100g = 0.7, CarbsPer100g = 10, FatPer100g = 0.2, FiberPer100g = 0.2,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 250 },
        new() { Name = "Apfelsaft", Aliases = ["Apple Juice"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 46, ProteinPer100g = 0.1, CarbsPer100g = 11, FatPer100g = 0.1, FiberPer100g = 0.1,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 250 },
        new() { Name = "Cola", Aliases = ["Coca Cola", "Pepsi"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 42, ProteinPer100g = 0, CarbsPer100g = 11, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Dose", DefaultPortionGrams = 330 },
        new() { Name = "Bier", Aliases = ["Beer", "Pils"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 43, ProteinPer100g = 0.5, CarbsPer100g = 3.6, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Flasche", DefaultPortionGrams = 500 },
        new() { Name = "Wein", Aliases = ["Wine", "Rotwein", "Weißwein"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 83, ProteinPer100g = 0.1, CarbsPer100g = 2.6, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 150 },
        new() { Name = "Kaffee", Aliases = ["Coffee"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 2, ProteinPer100g = 0.1, CarbsPer100g = 0, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Tasse", DefaultPortionGrams = 200 },

        // === SNACKS ===
        new() { Name = "Chips", Aliases = ["Kartoffelchips", "Crisps"], Category = FoodCategory.Snack,
            CaloriesPer100g = 536, ProteinPer100g = 7, CarbsPer100g = 53, FatPer100g = 33, FiberPer100g = 4.4,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 30 },
        new() { Name = "Popcorn", Aliases = [], Category = FoodCategory.Snack,
            CaloriesPer100g = 387, ProteinPer100g = 13, CarbsPer100g = 78, FatPer100g = 5, FiberPer100g = 15,
            DefaultPortion = "Portion", DefaultPortionGrams = 50 },
        new() { Name = "Cracker", Aliases = ["Salzstangen"], Category = FoodCategory.Snack,
            CaloriesPer100g = 420, ProteinPer100g = 10, CarbsPer100g = 72, FatPer100g = 10, FiberPer100g = 3,
            DefaultPortion = "Portion", DefaultPortionGrams = 30 },

        // === FAST FOOD ===
        new() { Name = "Pizza", Aliases = [], Category = FoodCategory.FastFood,
            CaloriesPer100g = 266, ProteinPer100g = 11, CarbsPer100g = 33, FatPer100g = 10, FiberPer100g = 2.3,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 120 },
        new() { Name = "Hamburger", Aliases = ["Burger", "Cheeseburger"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 295, ProteinPer100g = 17, CarbsPer100g = 24, FatPer100g = 14, FiberPer100g = 1.3,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 150 },
        new() { Name = "Pommes", Aliases = ["Pommes Frites", "French Fries", "Fritten"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 312, ProteinPer100g = 3.4, CarbsPer100g = 41, FatPer100g = 15, FiberPer100g = 3.8,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Döner", Aliases = ["Döner Kebab", "Kebab", "Dönertasche"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 215, ProteinPer100g = 13, CarbsPer100g = 18, FatPer100g = 10, FiberPer100g = 1.5,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 350 },
        new() { Name = "Hot Dog", Aliases = ["Hotdog"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 290, ProteinPer100g = 11, CarbsPer100g = 24, FatPer100g = 17, FiberPer100g = 1,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 150 },

        // === SÜSSIGKEITEN ===
        new() { Name = "Schokolade", Aliases = ["Chocolate", "Vollmilchschokolade"], Category = FoodCategory.Sweet,
            CaloriesPer100g = 535, ProteinPer100g = 8, CarbsPer100g = 60, FatPer100g = 30, FiberPer100g = 2,
            DefaultPortion = "1 Riegel", DefaultPortionGrams = 25 },
        new() { Name = "Gummibärchen", Aliases = ["Haribo", "Weingummi", "Gummy Bears"], Category = FoodCategory.Sweet,
            CaloriesPer100g = 343, ProteinPer100g = 7, CarbsPer100g = 77, FatPer100g = 0.5, FiberPer100g = 0,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 30 },
        new() { Name = "Kekse", Aliases = ["Cookies", "Butterkekse"], Category = FoodCategory.Sweet,
            CaloriesPer100g = 480, ProteinPer100g = 6, CarbsPer100g = 65, FatPer100g = 21, FiberPer100g = 2,
            DefaultPortion = "3 Stück", DefaultPortionGrams = 30 },
        new() { Name = "Eis", Aliases = ["Ice Cream", "Vanilleeis", "Eiscreme"], Category = FoodCategory.Sweet,
            CaloriesPer100g = 207, ProteinPer100g = 3.5, CarbsPer100g = 24, FatPer100g = 11, FiberPer100g = 0,
            DefaultPortion = "1 Kugel", DefaultPortionGrams = 50 },
        new() { Name = "Kuchen", Aliases = ["Cake", "Torte"], Category = FoodCategory.Sweet,
            CaloriesPer100g = 350, ProteinPer100g = 5, CarbsPer100g = 50, FatPer100g = 15, FiberPer100g = 1,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 100 },

        // === NÜSSE ===
        new() { Name = "Mandeln", Aliases = ["Almonds"], Category = FoodCategory.Nut,
            CaloriesPer100g = 579, ProteinPer100g = 21, CarbsPer100g = 22, FatPer100g = 50, FiberPer100g = 12,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 30 },
        new() { Name = "Walnüsse", Aliases = ["Walnuts"], Category = FoodCategory.Nut,
            CaloriesPer100g = 654, ProteinPer100g = 15, CarbsPer100g = 14, FatPer100g = 65, FiberPer100g = 7,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 30 },
        new() { Name = "Erdnüsse", Aliases = ["Peanuts", "Erdnuss"], Category = FoodCategory.Nut,
            CaloriesPer100g = 567, ProteinPer100g = 26, CarbsPer100g = 16, FatPer100g = 49, FiberPer100g = 8.5,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 30 },
        new() { Name = "Cashewnüsse", Aliases = ["Cashews"], Category = FoodCategory.Nut,
            CaloriesPer100g = 553, ProteinPer100g = 18, CarbsPer100g = 30, FatPer100g = 44, FiberPer100g = 3.3,
            DefaultPortion = "Handvoll", DefaultPortionGrams = 30 },

        // === HÜLSENFRÜCHTE ===
        new() { Name = "Linsen", Aliases = ["Lentils"], Category = FoodCategory.Legume,
            CaloriesPer100g = 116, ProteinPer100g = 9, CarbsPer100g = 20, FatPer100g = 0.4, FiberPer100g = 8,
            DefaultPortion = "Portion gekocht", DefaultPortionGrams = 150 },
        new() { Name = "Kichererbsen", Aliases = ["Chickpeas"], Category = FoodCategory.Legume,
            CaloriesPer100g = 164, ProteinPer100g = 9, CarbsPer100g = 27, FatPer100g = 2.6, FiberPer100g = 8,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Bohnen", Aliases = ["Kidney Bohnen", "Beans"], Category = FoodCategory.Legume,
            CaloriesPer100g = 127, ProteinPer100g = 9, CarbsPer100g = 22, FatPer100g = 0.5, FiberPer100g = 7,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Tofu", Aliases = [], Category = FoodCategory.Legume,
            CaloriesPer100g = 76, ProteinPer100g = 8, CarbsPer100g = 2, FatPer100g = 4.8, FiberPer100g = 0.3,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },

        // === SONSTIGES ===
        new() { Name = "Honig", Aliases = ["Honey"], Category = FoodCategory.Other,
            CaloriesPer100g = 304, ProteinPer100g = 0.3, CarbsPer100g = 82, FatPer100g = 0, FiberPer100g = 0.2,
            DefaultPortion = "1 EL", DefaultPortionGrams = 20 },
        new() { Name = "Olivenöl", Aliases = ["Olive Oil", "Öl"], Category = FoodCategory.Other,
            CaloriesPer100g = 884, ProteinPer100g = 0, CarbsPer100g = 0, FatPer100g = 100, FiberPer100g = 0,
            DefaultPortion = "1 EL", DefaultPortionGrams = 10 },
        new() { Name = "Nutella", Aliases = ["Nuss-Nougat-Creme"], Category = FoodCategory.Other,
            CaloriesPer100g = 539, ProteinPer100g = 6, CarbsPer100g = 58, FatPer100g = 31, FiberPer100g = 3,
            DefaultPortion = "1 EL", DefaultPortionGrams = 20 },
        new() { Name = "Marmelade", Aliases = ["Jam", "Konfitüre"], Category = FoodCategory.Other,
            CaloriesPer100g = 278, ProteinPer100g = 0.4, CarbsPer100g = 69, FatPer100g = 0.1, FiberPer100g = 1,
            DefaultPortion = "1 EL", DefaultPortionGrams = 20 },
        new() { Name = "Ketchup", Aliases = ["Tomato Ketchup"], Category = FoodCategory.Other,
            CaloriesPer100g = 112, ProteinPer100g = 1, CarbsPer100g = 26, FatPer100g = 0.1, FiberPer100g = 0.3,
            DefaultPortion = "1 EL", DefaultPortionGrams = 15 },
        new() { Name = "Mayonnaise", Aliases = ["Mayo"], Category = FoodCategory.Other,
            CaloriesPer100g = 680, ProteinPer100g = 1, CarbsPer100g = 1, FatPer100g = 75, FiberPer100g = 0,
            DefaultPortion = "1 EL", DefaultPortionGrams = 15 },

        // === ZUSÄTZLICHE GETREIDEPRODUKTE ===
        new() { Name = "Vollkornbrot", Aliases = ["Wholegrain Bread", "Schwarzbrot"], Category = FoodCategory.Grain,
            CaloriesPer100g = 219, ProteinPer100g = 7.5, CarbsPer100g = 41, FatPer100g = 2.2, FiberPer100g = 6.5,
            DefaultPortion = "2 Scheiben", DefaultPortionGrams = 80 },
        new() { Name = "Toast", Aliases = ["Toastbrot", "White Bread"], Category = FoodCategory.Grain,
            CaloriesPer100g = 266, ProteinPer100g = 8.4, CarbsPer100g = 49, FatPer100g = 3.3, FiberPer100g = 2.7,
            DefaultPortion = "2 Scheiben", DefaultPortionGrams = 50 },
        new() { Name = "Croissant", Aliases = ["Buttercroissant"], Category = FoodCategory.Grain,
            CaloriesPer100g = 406, ProteinPer100g = 8, CarbsPer100g = 43, FatPer100g = 21, FiberPer100g = 2.6,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 50 },
        new() { Name = "Cornflakes", Aliases = ["Corn Flakes"], Category = FoodCategory.Grain,
            CaloriesPer100g = 357, ProteinPer100g = 7, CarbsPer100g = 84, FatPer100g = 0.9, FiberPer100g = 3,
            DefaultPortion = "Schale", DefaultPortionGrams = 40 },
        new() { Name = "Quinoa", Aliases = ["Quinoa gekocht"], Category = FoodCategory.Grain,
            CaloriesPer100g = 120, ProteinPer100g = 4.4, CarbsPer100g = 21, FatPer100g = 1.9, FiberPer100g = 2.8,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },
        new() { Name = "Couscous", Aliases = ["Couscous gekocht"], Category = FoodCategory.Grain,
            CaloriesPer100g = 112, ProteinPer100g = 3.8, CarbsPer100g = 23, FatPer100g = 0.2, FiberPer100g = 1.4,
            DefaultPortion = "Portion", DefaultPortionGrams = 150 },

        // === ZUSÄTZLICHE MILCHPRODUKTE ===
        new() { Name = "Joghurt Natur", Aliases = ["Natural Yogurt", "Naturjoghurt"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 59, ProteinPer100g = 3.5, CarbsPer100g = 4.7, FatPer100g = 3.3, FiberPer100g = 0,
            DefaultPortion = "Becher", DefaultPortionGrams = 150 },
        new() { Name = "Joghurt Frucht", Aliases = ["Fruchtjoghurt", "Fruit Yogurt"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 88, ProteinPer100g = 3.2, CarbsPer100g = 13.5, FatPer100g = 2.5, FiberPer100g = 0.3,
            DefaultPortion = "Becher", DefaultPortionGrams = 150 },
        new() { Name = "Skyr", Aliases = ["Skyr Natur", "Icelandic Yogurt"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 66, ProteinPer100g = 11, CarbsPer100g = 4, FatPer100g = 0.2, FiberPer100g = 0,
            DefaultPortion = "Becher", DefaultPortionGrams = 150 },
        new() { Name = "Quark Magerquark", Aliases = ["Magerquark", "Low Fat Quark"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 67, ProteinPer100g = 13, CarbsPer100g = 4, FatPer100g = 0.3, FiberPer100g = 0,
            DefaultPortion = "Portion", DefaultPortionGrams = 200 },
        new() { Name = "Frischkäse", Aliases = ["Cream Cheese", "Philadelphia"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 206, ProteinPer100g = 5.5, CarbsPer100g = 4, FatPer100g = 20, FiberPer100g = 0,
            DefaultPortion = "1 EL", DefaultPortionGrams = 25 },
        new() { Name = "Sahne", Aliases = ["Schlagsahne", "Cream", "Heavy Cream"], Category = FoodCategory.Dairy,
            CaloriesPer100g = 309, ProteinPer100g = 2.4, CarbsPer100g = 3.4, FatPer100g = 31, FiberPer100g = 0,
            DefaultPortion = "1 EL", DefaultPortionGrams = 15 },

        // === ZUSÄTZLICHE SNACKS & SÜSSIGKEITEN ===
        new() { Name = "Schokoriegel", Aliases = ["Chocolate Bar", "Mars", "Snickers"], Category = FoodCategory.Snack,
            CaloriesPer100g = 479, ProteinPer100g = 4.4, CarbsPer100g = 61, FatPer100g = 24, FiberPer100g = 1.5,
            DefaultPortion = "1 Riegel", DefaultPortionGrams = 50 },
        new() { Name = "Eis Vanille", Aliases = ["Vanilla Ice Cream", "Vanilleeis"], Category = FoodCategory.Snack,
            CaloriesPer100g = 207, ProteinPer100g = 3.5, CarbsPer100g = 24, FatPer100g = 11, FiberPer100g = 0.5,
            DefaultPortion = "Kugel", DefaultPortionGrams = 75 },
        new() { Name = "Brownie", Aliases = ["Schokoladenbrownie", "Chocolate Brownie"], Category = FoodCategory.Snack,
            CaloriesPer100g = 466, ProteinPer100g = 5, CarbsPer100g = 54, FatPer100g = 26, FiberPer100g = 3,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 60 },
        new() { Name = "Donut", Aliases = ["Doughnut", "Berliner"], Category = FoodCategory.Snack,
            CaloriesPer100g = 452, ProteinPer100g = 4.9, CarbsPer100g = 51, FatPer100g = 25, FiberPer100g = 1.5,
            DefaultPortion = "1 Stück", DefaultPortionGrams = 70 },

        // === ZUSÄTZLICHES FAST FOOD ===
        new() { Name = "Pizza Salami", Aliases = ["Pepperoni Pizza"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 266, ProteinPer100g = 11, CarbsPer100g = 28, FatPer100g = 12, FiberPer100g = 2,
            DefaultPortion = "2 Stücke", DefaultPortionGrams = 200 },
        new() { Name = "Pizza Margherita", Aliases = ["Cheese Pizza"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 233, ProteinPer100g = 9, CarbsPer100g = 29, FatPer100g = 9, FiberPer100g = 2,
            DefaultPortion = "2 Stücke", DefaultPortionGrams = 200 },
        new() { Name = "Currywurst", Aliases = ["Currywurst mit Pommes"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 201, ProteinPer100g = 8, CarbsPer100g = 12, FatPer100g = 14, FiberPer100g = 0.8,
            DefaultPortion = "1 Portion", DefaultPortionGrams = 250 },
        new() { Name = "Chicken Nuggets", Aliases = ["McNuggets", "Hähnchennuggets"], Category = FoodCategory.FastFood,
            CaloriesPer100g = 296, ProteinPer100g = 15, CarbsPer100g = 18, FatPer100g = 18, FiberPer100g = 1,
            DefaultPortion = "6 Stück", DefaultPortionGrams = 100 },

        // === ZUSÄTZLICHE GETRÄNKE ===
        new() { Name = "Wein rot", Aliases = ["Red Wine", "Rotwein"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 85, ProteinPer100g = 0.1, CarbsPer100g = 2.6, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 150 },
        new() { Name = "Wein weiß", Aliases = ["White Wine", "Weißwein"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 82, ProteinPer100g = 0.1, CarbsPer100g = 2.6, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 150 },
        new() { Name = "Sekt", Aliases = ["Champagne", "Prosecco", "Sparkling Wine"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 78, ProteinPer100g = 0.2, CarbsPer100g = 1.5, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 100 },
        new() { Name = "Energy Drink", Aliases = ["Red Bull", "Energy Drink"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 45, ProteinPer100g = 0, CarbsPer100g = 11, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Dose", DefaultPortionGrams = 250 },
        new() { Name = "Kaffee schwarz", Aliases = ["Black Coffee", "Espresso"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 2, ProteinPer100g = 0.1, CarbsPer100g = 0, FatPer100g = 0, FiberPer100g = 0,
            DefaultPortion = "1 Tasse", DefaultPortionGrams = 200 },
        new() { Name = "Cappuccino", Aliases = ["Latte", "Milchkaffee"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 38, ProteinPer100g = 2, CarbsPer100g = 3.8, FatPer100g = 1.5, FiberPer100g = 0,
            DefaultPortion = "1 Tasse", DefaultPortionGrams = 240 },
        new() { Name = "Smoothie", Aliases = ["Fruit Smoothie", "Obstsmoothie"], Category = FoodCategory.Beverage,
            CaloriesPer100g = 54, ProteinPer100g = 0.6, CarbsPer100g = 13, FatPer100g = 0.2, FiberPer100g = 1,
            DefaultPortion = "1 Glas", DefaultPortionGrams = 250 }
    ];
}
