//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandwerkerImperium.Resources.Strings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandwerkerImperium.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppName => ResourceManager.GetString("AppName", resourceCulture) ?? "";

        public static string Home => ResourceManager.GetString("Home", resourceCulture) ?? "";

        public static string Stats => ResourceManager.GetString("Stats", resourceCulture) ?? "";

        public static string Shop => ResourceManager.GetString("Shop", resourceCulture) ?? "";

        public static string Settings => ResourceManager.GetString("Settings", resourceCulture) ?? "";

        public static string Carpenter => ResourceManager.GetString("Carpenter", resourceCulture) ?? "";

        public static string Plumber => ResourceManager.GetString("Plumber", resourceCulture) ?? "";

        public static string Electrician => ResourceManager.GetString("Electrician", resourceCulture) ?? "";

        public static string Painter => ResourceManager.GetString("Painter", resourceCulture) ?? "";

        public static string Roofer => ResourceManager.GetString("Roofer", resourceCulture) ?? "";

        public static string Contractor => ResourceManager.GetString("Contractor", resourceCulture) ?? "";

        public static string Level => ResourceManager.GetString("Level", resourceCulture) ?? "";

        public static string Upgrade => ResourceManager.GetString("Upgrade", resourceCulture) ?? "";

        public static string Workers => ResourceManager.GetString("Workers", resourceCulture) ?? "";

        public static string HireWorker => ResourceManager.GetString("HireWorker", resourceCulture) ?? "";

        public static string PerSecond => ResourceManager.GetString("PerSecond", resourceCulture) ?? "";

        public static string Locked => ResourceManager.GetString("Locked", resourceCulture) ?? "";

        public static string UnlocksAtLevel => ResourceManager.GetString("UnlocksAtLevel", resourceCulture) ?? "";

        public static string Orders => ResourceManager.GetString("Orders", resourceCulture) ?? "";

        public static string NewOrder => ResourceManager.GetString("NewOrder", resourceCulture) ?? "";

        public static string Start => ResourceManager.GetString("Start", resourceCulture) ?? "";

        public static string Reward => ResourceManager.GetString("Reward", resourceCulture) ?? "";

        public static string Difficulty => ResourceManager.GetString("Difficulty", resourceCulture) ?? "";

        public static string Sawing => ResourceManager.GetString("Sawing", resourceCulture) ?? "";

        public static string Planing => ResourceManager.GetString("Planing", resourceCulture) ?? "";

        public static string TileLaying => ResourceManager.GetString("TileLaying", resourceCulture) ?? "";

        public static string Measuring => ResourceManager.GetString("Measuring", resourceCulture) ?? "";

        public static string PipePuzzle => ResourceManager.GetString("PipePuzzle", resourceCulture) ?? "";

        public static string WiringGame => ResourceManager.GetString("WiringGame", resourceCulture) ?? "";

        public static string PaintingGame => ResourceManager.GetString("PaintingGame", resourceCulture) ?? "";

        public static string SawNow => ResourceManager.GetString("SawNow", resourceCulture) ?? "";

        public static string Perfect => ResourceManager.GetString("Perfect", resourceCulture) ?? "";

        public static string Good => ResourceManager.GetString("Good", resourceCulture) ?? "";

        public static string Ok => ResourceManager.GetString("Ok", resourceCulture) ?? "";

        public static string Miss => ResourceManager.GetString("Miss", resourceCulture) ?? "";

        public static string Continue => ResourceManager.GetString("Continue", resourceCulture) ?? "";

        public static string WatchAdForDouble => ResourceManager.GetString("WatchAdForDouble", resourceCulture) ?? "";

        public static string Bonus => ResourceManager.GetString("Bonus", resourceCulture) ?? "";

        public static string PerfectTiming => ResourceManager.GetString("PerfectTiming", resourceCulture) ?? "";

        public static string WelcomeBack => ResourceManager.GetString("WelcomeBack", resourceCulture) ?? "";

        public static string WhileYouWereAway => ResourceManager.GetString("WhileYouWereAway", resourceCulture) ?? "";

        public static string Collect => ResourceManager.GetString("Collect", resourceCulture) ?? "";

        public static string DoubleWithAd => ResourceManager.GetString("DoubleWithAd", resourceCulture) ?? "";

        public static string RemoveAds => ResourceManager.GetString("RemoveAds", resourceCulture) ?? "";

        public static string Premium => ResourceManager.GetString("Premium", resourceCulture) ?? "";

        public static string RestorePurchases => ResourceManager.GetString("RestorePurchases", resourceCulture) ?? "";

        public static string Achievements => ResourceManager.GetString("Achievements", resourceCulture) ?? "";

        public static string AchievementProgress => ResourceManager.GetString("AchievementProgress", resourceCulture) ?? "";

        public static string AchievementUnlocked => ResourceManager.GetString("AchievementUnlocked", resourceCulture) ?? "";

        public static string DailyReward => ResourceManager.GetString("DailyReward", resourceCulture) ?? "";

        public static string DailyStreak => ResourceManager.GetString("DailyStreak", resourceCulture) ?? "";

        public static string DayReward => ResourceManager.GetString("DayReward", resourceCulture) ?? "";

        public static string ClaimReward => ResourceManager.GetString("ClaimReward", resourceCulture) ?? "";

        public static string SpeedBoost1h => ResourceManager.GetString("SpeedBoost1h", resourceCulture) ?? "";

        public static string XpBoost1h => ResourceManager.GetString("XpBoost1h", resourceCulture) ?? "";

        public static string FreeWorker => ResourceManager.GetString("FreeWorker", resourceCulture) ?? "";

        public static string TutorialSkip => ResourceManager.GetString("TutorialSkip", resourceCulture) ?? "";

        public static string TutorialNext => ResourceManager.GetString("TutorialNext", resourceCulture) ?? "";

        public static string TutorialDone => ResourceManager.GetString("TutorialDone", resourceCulture) ?? "";

        public static string TutorialWelcomeTitle => ResourceManager.GetString("TutorialWelcomeTitle", resourceCulture) ?? "";

        public static string TutorialWelcomeDesc => ResourceManager.GetString("TutorialWelcomeDesc", resourceCulture) ?? "";

        public static string TutorialWorkshopsTitle => ResourceManager.GetString("TutorialWorkshopsTitle", resourceCulture) ?? "";

        public static string TutorialWorkshopsDesc => ResourceManager.GetString("TutorialWorkshopsDesc", resourceCulture) ?? "";

        public static string TutorialOrdersTitle => ResourceManager.GetString("TutorialOrdersTitle", resourceCulture) ?? "";

        public static string TutorialOrdersDesc => ResourceManager.GetString("TutorialOrdersDesc", resourceCulture) ?? "";

        public static string TutorialMiniGameTitle => ResourceManager.GetString("TutorialMiniGameTitle", resourceCulture) ?? "";

        public static string TutorialMiniGameDesc => ResourceManager.GetString("TutorialMiniGameDesc", resourceCulture) ?? "";

        public static string TutorialUpgradeTitle => ResourceManager.GetString("TutorialUpgradeTitle", resourceCulture) ?? "";

        public static string TutorialUpgradeDesc => ResourceManager.GetString("TutorialUpgradeDesc", resourceCulture) ?? "";

        public static string TutorialWorkersTitle => ResourceManager.GetString("TutorialWorkersTitle", resourceCulture) ?? "";

        public static string TutorialWorkersDesc => ResourceManager.GetString("TutorialWorkersDesc", resourceCulture) ?? "";

        public static string TutorialShopTitle => ResourceManager.GetString("TutorialShopTitle", resourceCulture) ?? "";

        public static string TutorialShopDesc => ResourceManager.GetString("TutorialShopDesc", resourceCulture) ?? "";

        public static string TutorialCompleteTitle => ResourceManager.GetString("TutorialCompleteTitle", resourceCulture) ?? "";

        public static string TutorialCompleteDesc => ResourceManager.GetString("TutorialCompleteDesc", resourceCulture) ?? "";

        public static string TotalXP => ResourceManager.GetString("TotalXP", resourceCulture) ?? "";

        public static string PlayTime => ResourceManager.GetString("PlayTime", resourceCulture) ?? "";

        public static string Balance => ResourceManager.GetString("Balance", resourceCulture) ?? "";

        public static string TotalEarned => ResourceManager.GetString("TotalEarned", resourceCulture) ?? "";

        public static string TotalSpent => ResourceManager.GetString("TotalSpent", resourceCulture) ?? "";

        public static string MiniGames => ResourceManager.GetString("MiniGames", resourceCulture) ?? "";

        public static string PerfectRate => ResourceManager.GetString("PerfectRate", resourceCulture) ?? "";

        public static string CurrentStreak => ResourceManager.GetString("CurrentStreak", resourceCulture) ?? "";

        public static string BestStreak => ResourceManager.GetString("BestStreak", resourceCulture) ?? "";

        public static string PrestigeLevel => ResourceManager.GetString("PrestigeLevel", resourceCulture) ?? "";

        public static string IncomeBonus => ResourceManager.GetString("IncomeBonus", resourceCulture) ?? "";

        public static string NextPrestigeBonus => ResourceManager.GetString("NextPrestigeBonus", resourceCulture) ?? "";

        public static string Workshops => ResourceManager.GetString("Workshops", resourceCulture) ?? "";

        public static string Income => ResourceManager.GetString("Income", resourceCulture) ?? "";

        public static string LevelProgress => ResourceManager.GetString("LevelProgress", resourceCulture) ?? "";

        public static string MaxLevelReached => ResourceManager.GetString("MaxLevelReached", resourceCulture) ?? "";

        public static string NoWorkersYet => ResourceManager.GetString("NoWorkersYet", resourceCulture) ?? "";

        public static string MaxWorkersReached => ResourceManager.GetString("MaxWorkersReached", resourceCulture) ?? "";

        public static string YouArePremium => ResourceManager.GetString("YouArePremium", resourceCulture) ?? "";

        public static string PremiumBenefits => ResourceManager.GetString("PremiumBenefits", resourceCulture) ?? "";

        public static string Audio => ResourceManager.GetString("Audio", resourceCulture) ?? "";

        public static string Sound => ResourceManager.GetString("Sound", resourceCulture) ?? "";

        public static string Vibration => ResourceManager.GetString("Vibration", resourceCulture) ?? "";

        public static string WarningDataLoss => ResourceManager.GetString("WarningDataLoss", resourceCulture) ?? "";

        public static string Version => ResourceManager.GetString("Version", resourceCulture) ?? "";

        public static string DevelopedBy => ResourceManager.GetString("DevelopedBy", resourceCulture) ?? "";

        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "";

        public static string Prestige => ResourceManager.GetString("Prestige", resourceCulture) ?? "";

        public static string PrestigeDescription => ResourceManager.GetString("PrestigeDescription", resourceCulture) ?? "";

        public static string CurrentBonus => ResourceManager.GetString("CurrentBonus", resourceCulture) ?? "";

        public static string NewBonus => ResourceManager.GetString("NewBonus", resourceCulture) ?? "";

        public static string Language => ResourceManager.GetString("Language", resourceCulture) ?? "";

        public static string RemoveAdsPrice => ResourceManager.GetString("RemoveAdsPrice", resourceCulture) ?? "";

        public static string PremiumBenefitNoAds => ResourceManager.GetString("PremiumBenefitNoAds", resourceCulture) ?? "";

        public static string PremiumBenefitOffline => ResourceManager.GetString("PremiumBenefitOffline", resourceCulture) ?? "";

        public static string PremiumBenefitSupport => ResourceManager.GetString("PremiumBenefitSupport", resourceCulture) ?? "";

        public static string Data => ResourceManager.GetString("Data", resourceCulture) ?? "";

        public static string DeleteSaveGame => ResourceManager.GetString("DeleteSaveGame", resourceCulture) ?? "";

        public static string About => ResourceManager.GetString("About", resourceCulture) ?? "";

        public static string PrivacyPolicy => ResourceManager.GetString("PrivacyPolicy", resourceCulture) ?? "";

        public static string SendFeedback => ResourceManager.GetString("SendFeedback", resourceCulture) ?? "";

        public static string AllRightsReserved => ResourceManager.GetString("AllRightsReserved", resourceCulture) ?? "";

        public static string OrderDetails => ResourceManager.GetString("OrderDetails", resourceCulture) ?? "";

        public static string MiniGamesRequiredFormat => ResourceManager.GetString("MiniGamesRequiredFormat", resourceCulture) ?? "";

        public static string Progress => ResourceManager.GetString("Progress", resourceCulture) ?? "";

        public static string StartOrder => ResourceManager.GetString("StartOrder", resourceCulture) ?? "";

        public static string ContinuePlaying => ResourceManager.GetString("ContinuePlaying", resourceCulture) ?? "";

        public static string CancelOrder => ResourceManager.GetString("CancelOrder", resourceCulture) ?? "";

        public static string OrderTip => ResourceManager.GetString("OrderTip", resourceCulture) ?? "";

        public static string ConnectSameColors => ResourceManager.GetString("ConnectSameColors", resourceCulture) ?? "";

        public static string SelectLeftThenRight => ResourceManager.GetString("SelectLeftThenRight", resourceCulture) ?? "";

        public static string ConnectPipes => ResourceManager.GetString("ConnectPipes", resourceCulture) ?? "";

        public static string TapToRotate => ResourceManager.GetString("TapToRotate", resourceCulture) ?? "";

        public static string PipesConnected => ResourceManager.GetString("PipesConnected", resourceCulture) ?? "";

        public static string TimeUp => ResourceManager.GetString("TimeUp", resourceCulture) ?? "";

        public static string DifficultyEasy => ResourceManager.GetString("DifficultyEasy", resourceCulture) ?? "";

        public static string DifficultyMedium => ResourceManager.GetString("DifficultyMedium", resourceCulture) ?? "";

        public static string DifficultyHard => ResourceManager.GetString("DifficultyHard", resourceCulture) ?? "";

        public static string DifficultyUnknown => ResourceManager.GetString("DifficultyUnknown", resourceCulture) ?? "";

        public static string ShopPremiumName => ResourceManager.GetString("ShopPremiumName", resourceCulture) ?? "";

        public static string ShopPremiumDesc => ResourceManager.GetString("ShopPremiumDesc", resourceCulture) ?? "";

        public static string ShopBooster30MinName => ResourceManager.GetString("ShopBooster30MinName", resourceCulture) ?? "";

        public static string ShopBooster30MinDesc => ResourceManager.GetString("ShopBooster30MinDesc", resourceCulture) ?? "";

        public static string ShopBooster2hName => ResourceManager.GetString("ShopBooster2hName", resourceCulture) ?? "";

        public static string ShopBooster2hDesc => ResourceManager.GetString("ShopBooster2hDesc", resourceCulture) ?? "";

        public static string ShopCashSmallName => ResourceManager.GetString("ShopCashSmallName", resourceCulture) ?? "";

        public static string ShopCashSmallDesc => ResourceManager.GetString("ShopCashSmallDesc", resourceCulture) ?? "";

        public static string ShopCashLargeName => ResourceManager.GetString("ShopCashLargeName", resourceCulture) ?? "";

        public static string ShopCashLargeDesc => ResourceManager.GetString("ShopCashLargeDesc", resourceCulture) ?? "";

        public static string ShopSkipTimeName => ResourceManager.GetString("ShopSkipTimeName", resourceCulture) ?? "";

        public static string ShopSkipTimeDesc => ResourceManager.GetString("ShopSkipTimeDesc", resourceCulture) ?? "";

        public static string WatchVideo => ResourceManager.GetString("WatchVideo", resourceCulture) ?? "";

        public static string AlreadyPurchased => ResourceManager.GetString("AlreadyPurchased", resourceCulture) ?? "";

        public static string AlreadyPurchasedDesc => ResourceManager.GetString("AlreadyPurchasedDesc", resourceCulture) ?? "";

        public static string WatchVideoQuestion => ResourceManager.GetString("WatchVideoQuestion", resourceCulture) ?? "";

        public static string Buy => ResourceManager.GetString("Buy", resourceCulture) ?? "";

        public static string Price => ResourceManager.GetString("Price", resourceCulture) ?? "";

        public static string BoosterActivated => ResourceManager.GetString("BoosterActivated", resourceCulture) ?? "";

        public static string BoosterActivatedDesc => ResourceManager.GetString("BoosterActivatedDesc", resourceCulture) ?? "";

        public static string MoneyReceived => ResourceManager.GetString("MoneyReceived", resourceCulture) ?? "";

        public static string MoneyReceivedFormat => ResourceManager.GetString("MoneyReceivedFormat", resourceCulture) ?? "";

        public static string TimeSkipped => ResourceManager.GetString("TimeSkipped", resourceCulture) ?? "";

        public static string ComingSoon => ResourceManager.GetString("ComingSoon", resourceCulture) ?? "";

        public static string ComingSoonDesc => ResourceManager.GetString("ComingSoonDesc", resourceCulture) ?? "";

        public static string ThankYou => ResourceManager.GetString("ThankYou", resourceCulture) ?? "";

        public static string ThankYouPremiumDesc => ResourceManager.GetString("ThankYouPremiumDesc", resourceCulture) ?? "";

        public static string Great => ResourceManager.GetString("Great", resourceCulture) ?? "";

        public static string PurchasesRestored => ResourceManager.GetString("PurchasesRestored", resourceCulture) ?? "";

        public static string PurchasesRestoredDesc => ResourceManager.GetString("PurchasesRestoredDesc", resourceCulture) ?? "";

        public static string NoPurchasesFound => ResourceManager.GetString("NoPurchasesFound", resourceCulture) ?? "";

        public static string NoPurchasesFoundDesc => ResourceManager.GetString("NoPurchasesFoundDesc", resourceCulture) ?? "";

        public static string PrestigeNotAvailable => ResourceManager.GetString("PrestigeNotAvailable", resourceCulture) ?? "";

        public static string PrestigeNotAvailableDesc => ResourceManager.GetString("PrestigeNotAvailableDesc", resourceCulture) ?? "";

        public static string ConfirmCancelOrder => ResourceManager.GetString("ConfirmCancelOrder", resourceCulture) ?? "";

        public static string ConfirmCancelOrderDesc => ResourceManager.GetString("ConfirmCancelOrderDesc", resourceCulture) ?? "";

        public static string YesCancel => ResourceManager.GetString("YesCancel", resourceCulture) ?? "";

        public static string No => ResourceManager.GetString("No", resourceCulture) ?? "";

        public static string FairPlayInfo => ResourceManager.GetString("FairPlayInfo", resourceCulture) ?? "";

        public static string WatchAdFree => ResourceManager.GetString("WatchAdFree", resourceCulture) ?? "";

        public static string Purchased => ResourceManager.GetString("Purchased", resourceCulture) ?? "";

        public static string Notice => ResourceManager.GetString("Notice", resourceCulture) ?? "";

        public static string TaskCount => ResourceManager.GetString("TaskCount", resourceCulture) ?? "";

        public static string Player => ResourceManager.GetString("Player", resourceCulture) ?? "";

        public static string MinLevelRequired => ResourceManager.GetString("MinLevelRequired", resourceCulture) ?? "";

        public static string WorkshopDetails => ResourceManager.GetString("WorkshopDetails", resourceCulture) ?? "";

        public static string PipePuzzleTitle => ResourceManager.GetString("PipePuzzleTitle", resourceCulture) ?? "";

        public static string PipePuzzleInstructions => ResourceManager.GetString("PipePuzzleInstructions", resourceCulture) ?? "";

        public static string WiringTitle => ResourceManager.GetString("WiringTitle", resourceCulture) ?? "";

        public static string WiringInstructions => ResourceManager.GetString("WiringInstructions", resourceCulture) ?? "";

        public static string PaintingTitle => ResourceManager.GetString("PaintingTitle", resourceCulture) ?? "";

        public static string PaintingInstructions => ResourceManager.GetString("PaintingInstructions", resourceCulture) ?? "";

        public static string PaintingPlayInstructions => ResourceManager.GetString("PaintingPlayInstructions", resourceCulture) ?? "";

        public static string PaintColor => ResourceManager.GetString("PaintColor", resourceCulture) ?? "";

        public static string Errors => ResourceManager.GetString("Errors", resourceCulture) ?? "";

        public static string StartGame => ResourceManager.GetString("StartGame", resourceCulture) ?? "";

        public static string Entrance => ResourceManager.GetString("Entrance", resourceCulture) ?? "";

        public static string Exit => ResourceManager.GetString("Exit", resourceCulture) ?? "";

        public static string StartPuzzle => ResourceManager.GetString("StartPuzzle", resourceCulture) ?? "";

        public static string Efficiency => ResourceManager.GetString("Efficiency", resourceCulture) ?? "";

        public static string SawingTitle => ResourceManager.GetString("SawingTitle", resourceCulture) ?? "";

        public static string SawingInstructions => ResourceManager.GetString("SawingInstructions", resourceCulture) ?? "";

        public static string PlaningTitle => ResourceManager.GetString("PlaningTitle", resourceCulture) ?? "";

        public static string TileLayingTitle => ResourceManager.GetString("TileLayingTitle", resourceCulture) ?? "";

        public static string MeasuringTitle => ResourceManager.GetString("MeasuringTitle", resourceCulture) ?? "";

        public static string ResetGameTitle => ResourceManager.GetString("ResetGameTitle", resourceCulture) ?? "";

        public static string ResetGameConfirmation => ResourceManager.GetString("ResetGameConfirmation", resourceCulture) ?? "";

        public static string YesReset => ResourceManager.GetString("YesReset", resourceCulture) ?? "";

        public static string GameResetCompleteTitle => ResourceManager.GetString("GameResetCompleteTitle", resourceCulture) ?? "";

        public static string GameResetComplete => ResourceManager.GetString("GameResetComplete", resourceCulture) ?? "";

        public static string Error => ResourceManager.GetString("Error", resourceCulture) ?? "";

        public static string PrivacyPolicyOpenError => ResourceManager.GetString("PrivacyPolicyOpenError", resourceCulture) ?? "";

        public static string EmailOpenError => ResourceManager.GetString("EmailOpenError", resourceCulture) ?? "";

        public static string FeedbackBody => ResourceManager.GetString("FeedbackBody", resourceCulture) ?? "";

        public static string RestoringPurchasesMessage => ResourceManager.GetString("RestoringPurchasesMessage", resourceCulture) ?? "";

        public static string MovesLabel => ResourceManager.GetString("MovesLabel", resourceCulture) ?? "";

        public static string ConnectedLabel => ResourceManager.GetString("ConnectedLabel", resourceCulture) ?? "";

        public static string MistakesLabel => ResourceManager.GetString("MistakesLabel", resourceCulture) ?? "";

        public static string PlaneNow => ResourceManager.GetString("PlaneNow", resourceCulture) ?? "";

        public static string LayNow => ResourceManager.GetString("LayNow", resourceCulture) ?? "";

        public static string MeasureNow => ResourceManager.GetString("MeasureNow", resourceCulture) ?? "";

        public static string StopInGreenZone => ResourceManager.GetString("StopInGreenZone", resourceCulture) ?? "";

        public static string StopForSmoothSurface => ResourceManager.GetString("StopForSmoothSurface", resourceCulture) ?? "";

        public static string StopAtPerfectMoment => ResourceManager.GetString("StopAtPerfectMoment", resourceCulture) ?? "";

        public static string StopAtRightLength => ResourceManager.GetString("StopAtRightLength", resourceCulture) ?? "";

        public static string LevelUpTitle => ResourceManager.GetString("LevelUpTitle", resourceCulture) ?? "";

        // Achievement Titles & Descriptions
        public static string AchFirstOrder => ResourceManager.GetString("AchFirstOrder", resourceCulture) ?? "";

        public static string AchFirstOrderDesc => ResourceManager.GetString("AchFirstOrderDesc", resourceCulture) ?? "";

        public static string AchOrders10 => ResourceManager.GetString("AchOrders10", resourceCulture) ?? "";

        public static string AchOrders10Desc => ResourceManager.GetString("AchOrders10Desc", resourceCulture) ?? "";

        public static string AchOrders50 => ResourceManager.GetString("AchOrders50", resourceCulture) ?? "";

        public static string AchOrders50Desc => ResourceManager.GetString("AchOrders50Desc", resourceCulture) ?? "";

        public static string AchOrders100 => ResourceManager.GetString("AchOrders100", resourceCulture) ?? "";

        public static string AchOrders100Desc => ResourceManager.GetString("AchOrders100Desc", resourceCulture) ?? "";

        public static string AchOrders500 => ResourceManager.GetString("AchOrders500", resourceCulture) ?? "";

        public static string AchOrders500Desc => ResourceManager.GetString("AchOrders500Desc", resourceCulture) ?? "";

        public static string AchPerfectFirst => ResourceManager.GetString("AchPerfectFirst", resourceCulture) ?? "";

        public static string AchPerfectFirstDesc => ResourceManager.GetString("AchPerfectFirstDesc", resourceCulture) ?? "";

        public static string AchPerfect10 => ResourceManager.GetString("AchPerfect10", resourceCulture) ?? "";

        public static string AchPerfect10Desc => ResourceManager.GetString("AchPerfect10Desc", resourceCulture) ?? "";

        public static string AchPerfect50 => ResourceManager.GetString("AchPerfect50", resourceCulture) ?? "";

        public static string AchPerfect50Desc => ResourceManager.GetString("AchPerfect50Desc", resourceCulture) ?? "";

        public static string AchStreak5 => ResourceManager.GetString("AchStreak5", resourceCulture) ?? "";

        public static string AchStreak5Desc => ResourceManager.GetString("AchStreak5Desc", resourceCulture) ?? "";

        public static string AchStreak10 => ResourceManager.GetString("AchStreak10", resourceCulture) ?? "";

        public static string AchStreak10Desc => ResourceManager.GetString("AchStreak10Desc", resourceCulture) ?? "";

        public static string AchGames100 => ResourceManager.GetString("AchGames100", resourceCulture) ?? "";

        public static string AchGames100Desc => ResourceManager.GetString("AchGames100Desc", resourceCulture) ?? "";

        public static string AchWorkshop10 => ResourceManager.GetString("AchWorkshop10", resourceCulture) ?? "";

        public static string AchWorkshop10Desc => ResourceManager.GetString("AchWorkshop10Desc", resourceCulture) ?? "";

        public static string AchWorkshop25 => ResourceManager.GetString("AchWorkshop25", resourceCulture) ?? "";

        public static string AchWorkshop25Desc => ResourceManager.GetString("AchWorkshop25Desc", resourceCulture) ?? "";

        public static string AchAllWorkshops => ResourceManager.GetString("AchAllWorkshops", resourceCulture) ?? "";

        public static string AchAllWorkshopsDesc => ResourceManager.GetString("AchAllWorkshopsDesc", resourceCulture) ?? "";

        public static string AchWorkerFirst => ResourceManager.GetString("AchWorkerFirst", resourceCulture) ?? "";

        public static string AchWorkerFirstDesc => ResourceManager.GetString("AchWorkerFirstDesc", resourceCulture) ?? "";

        public static string AchWorkers10 => ResourceManager.GetString("AchWorkers10", resourceCulture) ?? "";

        public static string AchWorkers10Desc => ResourceManager.GetString("AchWorkers10Desc", resourceCulture) ?? "";

        public static string AchWorkers25 => ResourceManager.GetString("AchWorkers25", resourceCulture) ?? "";

        public static string AchWorkers25Desc => ResourceManager.GetString("AchWorkers25Desc", resourceCulture) ?? "";

        public static string AchMoney1k => ResourceManager.GetString("AchMoney1k", resourceCulture) ?? "";

        public static string AchMoney1kDesc => ResourceManager.GetString("AchMoney1kDesc", resourceCulture) ?? "";

        public static string AchMoney10k => ResourceManager.GetString("AchMoney10k", resourceCulture) ?? "";

        public static string AchMoney10kDesc => ResourceManager.GetString("AchMoney10kDesc", resourceCulture) ?? "";

        public static string AchMoney100k => ResourceManager.GetString("AchMoney100k", resourceCulture) ?? "";

        public static string AchMoney100kDesc => ResourceManager.GetString("AchMoney100kDesc", resourceCulture) ?? "";

        public static string AchMoney1m => ResourceManager.GetString("AchMoney1m", resourceCulture) ?? "";

        public static string AchMoney1mDesc => ResourceManager.GetString("AchMoney1mDesc", resourceCulture) ?? "";

        public static string AchPlay1h => ResourceManager.GetString("AchPlay1h", resourceCulture) ?? "";

        public static string AchPlay1hDesc => ResourceManager.GetString("AchPlay1hDesc", resourceCulture) ?? "";

        public static string AchPlay10h => ResourceManager.GetString("AchPlay10h", resourceCulture) ?? "";

        public static string AchPlay10hDesc => ResourceManager.GetString("AchPlay10hDesc", resourceCulture) ?? "";

        public static string AchDaily7 => ResourceManager.GetString("AchDaily7", resourceCulture) ?? "";

        public static string AchDaily7Desc => ResourceManager.GetString("AchDaily7Desc", resourceCulture) ?? "";

        public static string AchLevel10 => ResourceManager.GetString("AchLevel10", resourceCulture) ?? "";

        public static string AchLevel10Desc => ResourceManager.GetString("AchLevel10Desc", resourceCulture) ?? "";

        public static string AchLevel25 => ResourceManager.GetString("AchLevel25", resourceCulture) ?? "";

        public static string AchLevel25Desc => ResourceManager.GetString("AchLevel25Desc", resourceCulture) ?? "";

        public static string AchLevel50 => ResourceManager.GetString("AchLevel50", resourceCulture) ?? "";

        public static string AchLevel50Desc => ResourceManager.GetString("AchLevel50Desc", resourceCulture) ?? "";

        public static string AchPrestige1 => ResourceManager.GetString("AchPrestige1", resourceCulture) ?? "";

        public static string AchPrestige1Desc => ResourceManager.GetString("AchPrestige1Desc", resourceCulture) ?? "";

        // Order Titles
        public static string order_shelf => ResourceManager.GetString("order_shelf", resourceCulture) ?? "";

        public static string order_cabinet => ResourceManager.GetString("order_cabinet", resourceCulture) ?? "";

        public static string order_table => ResourceManager.GetString("order_table", resourceCulture) ?? "";

        public static string order_deck => ResourceManager.GetString("order_deck", resourceCulture) ?? "";

        public static string order_shed => ResourceManager.GetString("order_shed", resourceCulture) ?? "";

        public static string order_faucet => ResourceManager.GetString("order_faucet", resourceCulture) ?? "";

        public static string order_toilet => ResourceManager.GetString("order_toilet", resourceCulture) ?? "";

        public static string order_shower => ResourceManager.GetString("order_shower", resourceCulture) ?? "";

        public static string order_bathroom => ResourceManager.GetString("order_bathroom", resourceCulture) ?? "";

        public static string order_outlet => ResourceManager.GetString("order_outlet", resourceCulture) ?? "";

        public static string order_light => ResourceManager.GetString("order_light", resourceCulture) ?? "";

        public static string order_panel => ResourceManager.GetString("order_panel", resourceCulture) ?? "";

        public static string order_smart_home => ResourceManager.GetString("order_smart_home", resourceCulture) ?? "";

        public static string order_room => ResourceManager.GetString("order_room", resourceCulture) ?? "";

        public static string order_exterior => ResourceManager.GetString("order_exterior", resourceCulture) ?? "";

        public static string order_house => ResourceManager.GetString("order_house", resourceCulture) ?? "";

        public static string order_repair_roof => ResourceManager.GetString("order_repair_roof", resourceCulture) ?? "";

        public static string order_new_roof => ResourceManager.GetString("order_new_roof", resourceCulture) ?? "";

        public static string order_renovation => ResourceManager.GetString("order_renovation", resourceCulture) ?? "";

        public static string order_addition => ResourceManager.GetString("order_addition", resourceCulture) ?? "";

        // Task Descriptions
        public static string task_sawing => ResourceManager.GetString("task_sawing", resourceCulture) ?? "";

        public static string task_pipepuzzle => ResourceManager.GetString("task_pipepuzzle", resourceCulture) ?? "";

        public static string task_wiringgame => ResourceManager.GetString("task_wiringgame", resourceCulture) ?? "";

        public static string task_paintinggame => ResourceManager.GetString("task_paintinggame", resourceCulture) ?? "";

        public static string task_tilelaying => ResourceManager.GetString("task_tilelaying", resourceCulture) ?? "";

        public static string task_measuring => ResourceManager.GetString("task_measuring", resourceCulture) ?? "";

        public static string task_planing => ResourceManager.GetString("task_planing", resourceCulture) ?? "";

        public static string Input => ResourceManager.GetString("Input", resourceCulture) ?? "";

        public static string Output => ResourceManager.GetString("Output", resourceCulture) ?? "";

        public static string StartResearch => ResourceManager.GetString("StartResearch", resourceCulture) ?? "";

        public static string CurrentResearch => ResourceManager.GetString("CurrentResearch", resourceCulture) ?? "";

        public static string ResearchBetterSaws => ResourceManager.GetString("ResearchBetterSaws", resourceCulture) ?? "";

        public static string ResearchPrecisionTools => ResourceManager.GetString("ResearchPrecisionTools", resourceCulture) ?? "";

        public static string ResearchPowerTools => ResourceManager.GetString("ResearchPowerTools", resourceCulture) ?? "";

        public static string ResearchAutoMaterial => ResourceManager.GetString("ResearchAutoMaterial", resourceCulture) ?? "";

        public static string ResearchAdvancedMachinery => ResourceManager.GetString("ResearchAdvancedMachinery", resourceCulture) ?? "";

        public static string ResearchQualityControl => ResourceManager.GetString("ResearchQualityControl", resourceCulture) ?? "";

        public static string ResearchCncMachines => ResourceManager.GetString("ResearchCncMachines", resourceCulture) ?? "";

        public static string ResearchLaserCutting => ResourceManager.GetString("ResearchLaserCutting", resourceCulture) ?? "";

        public static string ResearchRobotics => ResourceManager.GetString("ResearchRobotics", resourceCulture) ?? "";

        public static string Research3dPrinting => ResourceManager.GetString("Research3dPrinting", resourceCulture) ?? "";

        public static string ResearchSmartFactory => ResourceManager.GetString("ResearchSmartFactory", resourceCulture) ?? "";

        public static string ResearchNanotech => ResourceManager.GetString("ResearchNanotech", resourceCulture) ?? "";

        public static string ResearchQuantumMeasure => ResourceManager.GetString("ResearchQuantumMeasure", resourceCulture) ?? "";

        public static string ResearchAiAssisted => ResourceManager.GetString("ResearchAiAssisted", resourceCulture) ?? "";

        public static string ResearchMasterCraftsman => ResourceManager.GetString("ResearchMasterCraftsman", resourceCulture) ?? "";

        public static string ResearchBetterSawsDesc => ResourceManager.GetString("ResearchBetterSawsDesc", resourceCulture) ?? "";

        public static string ResearchPrecisionToolsDesc => ResourceManager.GetString("ResearchPrecisionToolsDesc", resourceCulture) ?? "";

        public static string ResearchPowerToolsDesc => ResourceManager.GetString("ResearchPowerToolsDesc", resourceCulture) ?? "";

        public static string ResearchAutoMaterialDesc => ResourceManager.GetString("ResearchAutoMaterialDesc", resourceCulture) ?? "";

        public static string ResearchAdvancedMachineryDesc => ResourceManager.GetString("ResearchAdvancedMachineryDesc", resourceCulture) ?? "";

        public static string ResearchQualityControlDesc => ResourceManager.GetString("ResearchQualityControlDesc", resourceCulture) ?? "";

        public static string ResearchCncMachinesDesc => ResourceManager.GetString("ResearchCncMachinesDesc", resourceCulture) ?? "";

        public static string ResearchLaserCuttingDesc => ResourceManager.GetString("ResearchLaserCuttingDesc", resourceCulture) ?? "";

        public static string ResearchRoboticsDesc => ResourceManager.GetString("ResearchRoboticsDesc", resourceCulture) ?? "";

        public static string Research3dPrintingDesc => ResourceManager.GetString("Research3dPrintingDesc", resourceCulture) ?? "";

        public static string ResearchSmartFactoryDesc => ResourceManager.GetString("ResearchSmartFactoryDesc", resourceCulture) ?? "";

        public static string ResearchNanotechDesc => ResourceManager.GetString("ResearchNanotechDesc", resourceCulture) ?? "";

        public static string ResearchQuantumMeasureDesc => ResourceManager.GetString("ResearchQuantumMeasureDesc", resourceCulture) ?? "";

        public static string ResearchAiAssistedDesc => ResourceManager.GetString("ResearchAiAssistedDesc", resourceCulture) ?? "";

        public static string ResearchMasterCraftsmanDesc => ResourceManager.GetString("ResearchMasterCraftsmanDesc", resourceCulture) ?? "";

        public static string ResearchHrBasics => ResourceManager.GetString("ResearchHrBasics", resourceCulture) ?? "";

        public static string ResearchTeamBuilding => ResourceManager.GetString("ResearchTeamBuilding", resourceCulture) ?? "";

        public static string ResearchMotivation => ResourceManager.GetString("ResearchMotivation", resourceCulture) ?? "";

        public static string ResearchHeadhunter => ResourceManager.GetString("ResearchHeadhunter", resourceCulture) ?? "";

        public static string ResearchTrainingProgram => ResourceManager.GetString("ResearchTrainingProgram", resourceCulture) ?? "";

        public static string ResearchWorkLifeBalance => ResourceManager.GetString("ResearchWorkLifeBalance", resourceCulture) ?? "";

        public static string ResearchAutoAssign => ResourceManager.GetString("ResearchAutoAssign", resourceCulture) ?? "";

        public static string ResearchTalentScout => ResourceManager.GetString("ResearchTalentScout", resourceCulture) ?? "";

        public static string ResearchLeadership => ResourceManager.GetString("ResearchLeadership", resourceCulture) ?? "";

        public static string ResearchEliteRecruitment => ResourceManager.GetString("ResearchEliteRecruitment", resourceCulture) ?? "";

        public static string ResearchMentorship => ResourceManager.GetString("ResearchMentorship", resourceCulture) ?? "";

        public static string ResearchCorporateCulture => ResourceManager.GetString("ResearchCorporateCulture", resourceCulture) ?? "";

        public static string ResearchGlobalTalent => ResourceManager.GetString("ResearchGlobalTalent", resourceCulture) ?? "";

        public static string ResearchAiManagement => ResourceManager.GetString("ResearchAiManagement", resourceCulture) ?? "";

        public static string ResearchMasterManager => ResourceManager.GetString("ResearchMasterManager", resourceCulture) ?? "";

        public static string ResearchHrBasicsDesc => ResourceManager.GetString("ResearchHrBasicsDesc", resourceCulture) ?? "";

        public static string ResearchTeamBuildingDesc => ResourceManager.GetString("ResearchTeamBuildingDesc", resourceCulture) ?? "";

        public static string ResearchMotivationDesc => ResourceManager.GetString("ResearchMotivationDesc", resourceCulture) ?? "";

        public static string ResearchHeadhunterDesc => ResourceManager.GetString("ResearchHeadhunterDesc", resourceCulture) ?? "";

        public static string ResearchTrainingProgramDesc => ResourceManager.GetString("ResearchTrainingProgramDesc", resourceCulture) ?? "";

        public static string ResearchWorkLifeBalanceDesc => ResourceManager.GetString("ResearchWorkLifeBalanceDesc", resourceCulture) ?? "";

        public static string ResearchAutoAssignDesc => ResourceManager.GetString("ResearchAutoAssignDesc", resourceCulture) ?? "";

        public static string ResearchTalentScoutDesc => ResourceManager.GetString("ResearchTalentScoutDesc", resourceCulture) ?? "";

        public static string ResearchLeadershipDesc => ResourceManager.GetString("ResearchLeadershipDesc", resourceCulture) ?? "";

        public static string ResearchEliteRecruitmentDesc => ResourceManager.GetString("ResearchEliteRecruitmentDesc", resourceCulture) ?? "";

        public static string ResearchMentorshipDesc => ResourceManager.GetString("ResearchMentorshipDesc", resourceCulture) ?? "";

        public static string ResearchCorporateCultureDesc => ResourceManager.GetString("ResearchCorporateCultureDesc", resourceCulture) ?? "";

        public static string ResearchGlobalTalentDesc => ResourceManager.GetString("ResearchGlobalTalentDesc", resourceCulture) ?? "";

        public static string ResearchAiManagementDesc => ResourceManager.GetString("ResearchAiManagementDesc", resourceCulture) ?? "";

        public static string ResearchMasterManagerDesc => ResourceManager.GetString("ResearchMasterManagerDesc", resourceCulture) ?? "";

        public static string ResearchLocalAds => ResourceManager.GetString("ResearchLocalAds", resourceCulture) ?? "";

        public static string ResearchOnlinePresence => ResourceManager.GetString("ResearchOnlinePresence", resourceCulture) ?? "";

        public static string ResearchBranding => ResourceManager.GetString("ResearchBranding", resourceCulture) ?? "";

        public static string ResearchReferralProgram => ResourceManager.GetString("ResearchReferralProgram", resourceCulture) ?? "";

        public static string ResearchPremiumBrand => ResourceManager.GetString("ResearchPremiumBrand", resourceCulture) ?? "";

        public static string ResearchSocialMedia => ResourceManager.GetString("ResearchSocialMedia", resourceCulture) ?? "";

        public static string ResearchPublicRelations => ResourceManager.GetString("ResearchPublicRelations", resourceCulture) ?? "";

        public static string ResearchTvCampaign => ResourceManager.GetString("ResearchTvCampaign", resourceCulture) ?? "";

        public static string ResearchInternational => ResourceManager.GetString("ResearchInternational", resourceCulture) ?? "";

        public static string ResearchLuxuryBrand => ResourceManager.GetString("ResearchLuxuryBrand", resourceCulture) ?? "";

        public static string ResearchFranchise => ResourceManager.GetString("ResearchFranchise", resourceCulture) ?? "";

        public static string ResearchGlobalBrand => ResourceManager.GetString("ResearchGlobalBrand", resourceCulture) ?? "";

        public static string ResearchCelebEndorsement => ResourceManager.GetString("ResearchCelebEndorsement", resourceCulture) ?? "";

        public static string ResearchMonopoly => ResourceManager.GetString("ResearchMonopoly", resourceCulture) ?? "";

        public static string ResearchMarketDomination => ResourceManager.GetString("ResearchMarketDomination", resourceCulture) ?? "";

        public static string ResearchLocalAdsDesc => ResourceManager.GetString("ResearchLocalAdsDesc", resourceCulture) ?? "";

        public static string ResearchOnlinePresenceDesc => ResourceManager.GetString("ResearchOnlinePresenceDesc", resourceCulture) ?? "";

        public static string ResearchBrandingDesc => ResourceManager.GetString("ResearchBrandingDesc", resourceCulture) ?? "";

        public static string ResearchReferralProgramDesc => ResourceManager.GetString("ResearchReferralProgramDesc", resourceCulture) ?? "";

        public static string ResearchPremiumBrandDesc => ResourceManager.GetString("ResearchPremiumBrandDesc", resourceCulture) ?? "";

        public static string ResearchSocialMediaDesc => ResourceManager.GetString("ResearchSocialMediaDesc", resourceCulture) ?? "";

        public static string ResearchPublicRelationsDesc => ResourceManager.GetString("ResearchPublicRelationsDesc", resourceCulture) ?? "";

        public static string ResearchTvCampaignDesc => ResourceManager.GetString("ResearchTvCampaignDesc", resourceCulture) ?? "";

        public static string ResearchInternationalDesc => ResourceManager.GetString("ResearchInternationalDesc", resourceCulture) ?? "";

        public static string ResearchLuxuryBrandDesc => ResourceManager.GetString("ResearchLuxuryBrandDesc", resourceCulture) ?? "";

        public static string ResearchFranchiseDesc => ResourceManager.GetString("ResearchFranchiseDesc", resourceCulture) ?? "";

        public static string ResearchGlobalBrandDesc => ResourceManager.GetString("ResearchGlobalBrandDesc", resourceCulture) ?? "";

        public static string ResearchCelebEndorsementDesc => ResourceManager.GetString("ResearchCelebEndorsementDesc", resourceCulture) ?? "";

        public static string ResearchMonopolyDesc => ResourceManager.GetString("ResearchMonopolyDesc", resourceCulture) ?? "";

        public static string ResearchMarketDominationDesc => ResourceManager.GetString("ResearchMarketDominationDesc", resourceCulture) ?? "";

        public static string QuickJobs => ResourceManager.GetString("QuickJobs", resourceCulture) ?? "";

        public static string QuickRepair => ResourceManager.GetString("QuickRepair", resourceCulture) ?? "";

        public static string QuickFix => ResourceManager.GetString("QuickFix", resourceCulture) ?? "";

        public static string ExpressService => ResourceManager.GetString("ExpressService", resourceCulture) ?? "";

        public static string SmallOrder => ResourceManager.GetString("SmallOrder", resourceCulture) ?? "";

        public static string QuickMeasure => ResourceManager.GetString("QuickMeasure", resourceCulture) ?? "";

        public static string QuickInstall => ResourceManager.GetString("QuickInstall", resourceCulture) ?? "";

        public static string QuickPaint => ResourceManager.GetString("QuickPaint", resourceCulture) ?? "";

        public static string QuickCheck => ResourceManager.GetString("QuickCheck", resourceCulture) ?? "";

        public static string DailyChallenges => ResourceManager.GetString("DailyChallenges", resourceCulture) ?? "";

        public static string ChallengeCompleteOrders => ResourceManager.GetString("ChallengeCompleteOrders", resourceCulture) ?? "";

        public static string ChallengeEarnMoney => ResourceManager.GetString("ChallengeEarnMoney", resourceCulture) ?? "";

        public static string ChallengeUpgradeWorkshop => ResourceManager.GetString("ChallengeUpgradeWorkshop", resourceCulture) ?? "";

        public static string ChallengeHireWorker => ResourceManager.GetString("ChallengeHireWorker", resourceCulture) ?? "";

        public static string ChallengeCompleteQuickJob => ResourceManager.GetString("ChallengeCompleteQuickJob", resourceCulture) ?? "";

        public static string ChallengePlayMiniGames => ResourceManager.GetString("ChallengePlayMiniGames", resourceCulture) ?? "";

        public static string ChallengeAchieveScore => ResourceManager.GetString("ChallengeAchieveScore", resourceCulture) ?? "";

        public static string AllChallengesBonus => ResourceManager.GetString("AllChallengesBonus", resourceCulture) ?? "";

        public static string Tools => ResourceManager.GetString("Tools", resourceCulture) ?? "";

        public static string ToolSaw => ResourceManager.GetString("ToolSaw", resourceCulture) ?? "";

        public static string ToolPipeWrench => ResourceManager.GetString("ToolPipeWrench", resourceCulture) ?? "";

        public static string ToolScrewdriver => ResourceManager.GetString("ToolScrewdriver", resourceCulture) ?? "";

        public static string ToolPaintbrush => ResourceManager.GetString("ToolPaintbrush", resourceCulture) ?? "";

        public static string ToolEffectZone => ResourceManager.GetString("ToolEffectZone", resourceCulture) ?? "";

        public static string ToolEffectTime => ResourceManager.GetString("ToolEffectTime", resourceCulture) ?? "";

        public static string ToolUpgrade => ResourceManager.GetString("ToolUpgrade", resourceCulture) ?? "";

        public static string ToolMaxLevel => ResourceManager.GetString("ToolMaxLevel", resourceCulture) ?? "";

        public static string NextRotation => ResourceManager.GetString("NextRotation", resourceCulture) ?? "";

        public static string Info => ResourceManager.GetString("Info", resourceCulture) ?? "";

        public static string WatchAdToRefresh => ResourceManager.GetString("WatchAdToRefresh", resourceCulture) ?? "";

        internal static string GoldenScrews {
            get {
                return ResourceManager.GetString("GoldenScrews", resourceCulture);
            }
        }

        internal static string ShopGoldenScrewsAdName {
            get {
                return ResourceManager.GetString("ShopGoldenScrewsAdName", resourceCulture);
            }
        }

        internal static string ShopGoldenScrewsAdDesc {
            get {
                return ResourceManager.GetString("ShopGoldenScrewsAdDesc", resourceCulture);
            }
        }

        internal static string ShopGoldenScrews50Name {
            get {
                return ResourceManager.GetString("ShopGoldenScrews50Name", resourceCulture);
            }
        }

        internal static string ShopGoldenScrews50Desc {
            get {
                return ResourceManager.GetString("ShopGoldenScrews50Desc", resourceCulture);
            }
        }

        internal static string ShopGoldenScrews150Name {
            get {
                return ResourceManager.GetString("ShopGoldenScrews150Name", resourceCulture);
            }
        }

        internal static string ShopGoldenScrews150Desc {
            get {
                return ResourceManager.GetString("ShopGoldenScrews150Desc", resourceCulture);
            }
        }

        internal static string ShopGoldenScrews450Name {
            get {
                return ResourceManager.GetString("ShopGoldenScrews450Name", resourceCulture);
            }
        }

        internal static string ShopGoldenScrews450Desc {
            get {
                return ResourceManager.GetString("ShopGoldenScrews450Desc", resourceCulture);
            }
        }

        internal static string InstantFinish {
            get {
                return ResourceManager.GetString("InstantFinish", resourceCulture);
            }
        }

        internal static string InstantFinishDesc {
            get {
                return ResourceManager.GetString("InstantFinishDesc", resourceCulture);
            }
        }

        internal static string HiringScrewCost {
            get {
                return ResourceManager.GetString("HiringScrewCost", resourceCulture);
            }
        }

        internal static string GoldenScrewsReceivedFormat {
            get {
                return ResourceManager.GetString("GoldenScrewsReceivedFormat", resourceCulture);
            }
        }

        internal static string NotEnoughScrews {
            get {
                return ResourceManager.GetString("NotEnoughScrews", resourceCulture);
            }
        }

        internal static string NotEnoughScrewsDesc {
            get {
                return ResourceManager.GetString("NotEnoughScrewsDesc", resourceCulture);
            }
        }

        internal static string SelectWorkshop {
            get {
                return ResourceManager.GetString("SelectWorkshop", resourceCulture);
            }
        }

        public static string AdVideoNotAvailableTitle => ResourceManager.GetString("AdVideoNotAvailableTitle", resourceCulture) ?? "";

        public static string AdVideoNotAvailableMessage => ResourceManager.GetString("AdVideoNotAvailableMessage", resourceCulture) ?? "";
    }
}
