//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTimePro.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkTimePro.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add entry ähnelt.
        /// </summary>
        internal static string AddEntry {
            get {
                return ResourceManager.GetString("AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WorkTime Pro ähnelt.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto break ähnelt.
        /// </summary>
        internal static string AutoPause {
            get {
                return ResourceManager.GetString("AutoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto break added ähnelt.
        /// </summary>
        internal static string AutoPauseAdded {
            get {
                return ResourceManager.GetString("AutoPauseAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After hours ähnelt.
        /// </summary>
        internal static string AutoPauseAfterHours {
            get {
                return ResourceManager.GetString("AutoPauseAfterHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically add legally required break time ähnelt.
        /// </summary>
        internal static string AutoPauseDescription {
            get {
                return ResourceManager.GetString("AutoPauseDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto breaks are calculated automatically and cannot be deleted manually. ähnelt.
        /// </summary>
        internal static string AutoPauseCannotDelete {
            get {
                return ResourceManager.GetString("AutoPauseCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto break enabled ähnelt.
        /// </summary>
        internal static string AutoPauseEnabled {
            get {
                return ResourceManager.GetString("AutoPauseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically added (legal requirement) ähnelt.
        /// </summary>
        internal static string AutoPauseLegal {
            get {
                return ResourceManager.GetString("AutoPauseLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto break ähnelt.
        /// </summary>
        internal static string AutoPauseSettings {
            get {
                return ResourceManager.GetString("AutoPauseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average per day ähnelt.
        /// </summary>
        internal static string AveragePerDay {
            get {
                return ResourceManager.GetString("AveragePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break ähnelt.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break reminder ähnelt.
        /// </summary>
        internal static string BreakReminder {
            get {
                return ResourceManager.GetString("BreakReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy Premium ähnelt.
        /// </summary>
        internal static string BuyPremium {
            get {
                return ResourceManager.GetString("BuyPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar ähnelt.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check-in ähnelt.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check-out ähnelt.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close month ähnelt.
        /// </summary>
        internal static string CloseMonth {
            get {
                return ResourceManager.GetString("CloseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cumulative balance ähnelt.
        /// </summary>
        internal static string CumulativeBalance {
            get {
                return ResourceManager.GetString("CumulativeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily target (hours) ähnelt.
        /// </summary>
        internal static string DailyTarget {
            get {
                return ResourceManager.GetString("DailyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day details ähnelt.
        /// </summary>
        internal static string DayDetails {
            get {
                return ResourceManager.GetString("DayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day progress ähnelt.
        /// </summary>
        internal static string DayProgress {
            get {
                return ResourceManager.GetString("DayProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Business trip ähnelt.
        /// </summary>
        internal static string DayStatus_BusinessTrip {
            get {
                return ResourceManager.GetString("DayStatus_BusinessTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holiday ähnelt.
        /// </summary>
        internal static string DayStatus_Holiday {
            get {
                return ResourceManager.GetString("DayStatus_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home office ähnelt.
        /// </summary>
        internal static string DayStatus_HomeOffice {
            get {
                return ResourceManager.GetString("DayStatus_HomeOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sick ähnelt.
        /// </summary>
        internal static string DayStatus_Sick {
            get {
                return ResourceManager.GetString("DayStatus_Sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation ähnelt.
        /// </summary>
        internal static string DayStatus_Vacation {
            get {
                return ResourceManager.GetString("DayStatus_Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekend ähnelt.
        /// </summary>
        internal static string DayStatus_Weekend {
            get {
                return ResourceManager.GetString("DayStatus_Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work day ähnelt.
        /// </summary>
        internal static string DayStatus_WorkDay {
            get {
                return ResourceManager.GetString("DayStatus_WorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete entry ähnelt.
        /// </summary>
        internal static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the entry at {0}? ähnelt.
        /// </summary>
        internal static string DeleteEntryConfirm {
            get {
                return ResourceManager.GetString("DeleteEntryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete break ähnelt.
        /// </summary>
        internal static string DeletePause {
            get {
                return ResourceManager.GetString("DeletePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the break from {0} to {1}? ähnelt.
        /// </summary>
        internal static string DeletePauseConfirm {
            get {
                return ResourceManager.GetString("DeletePauseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of day! ähnelt.
        /// </summary>
        internal static string EndOfDay {
            get {
                return ResourceManager.GetString("EndOfDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End break ähnelt.
        /// </summary>
        internal static string EndPause {
            get {
                return ResourceManager.GetString("EndPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End of work ähnelt.
        /// </summary>
        internal static string EveningReminder {
            get {
                return ResourceManager.GetString("EveningReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free version with ads ähnelt.
        /// </summary>
        internal static string FreeVersion {
            get {
                return ResourceManager.GetString("FreeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fri ähnelt.
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friday ähnelt.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holidays ähnelt.
        /// </summary>
        internal static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal compliance check ähnelt.
        /// </summary>
        internal static string LegalCompliance {
            get {
                return ResourceManager.GetString("LegalCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show warnings for violations (max. 10h/day, min. 11h rest) ähnelt.
        /// </summary>
        internal static string LegalComplianceDescription {
            get {
                return ResourceManager.GetString("LegalComplianceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working Hours Act (ArbZG) ähnelt.
        /// </summary>
        internal static string LegalSourceArbZG {
            get {
                return ResourceManager.GetString("LegalSourceArbZG", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Public holidays (BMI) ähnelt.
        /// </summary>
        internal static string LegalSourceHolidays {
            get {
                return ResourceManager.GetString("LegalSourceHolidays", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legal sources ähnelt.
        /// </summary>
        internal static string LegalSources {
            get {
                return ResourceManager.GetString("LegalSources", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break regulations description ähnelt.
        /// </summary>
        internal static string LegalSourcesDescription {
            get {
                return ResourceManager.GetString("LegalSourcesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time law notices ähnelt.
        /// </summary>
        internal static string LegalWarnings {
            get {
                return ResourceManager.GetString("LegalWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legend ähnelt.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual break ähnelt.
        /// </summary>
        internal static string ManualPause {
            get {
                return ResourceManager.GetString("ManualPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily work time over {0}h (Work Time Act) ähnelt.
        /// </summary>
        internal static string MaxDailyHoursExceeded {
            get {
                return ResourceManager.GetString("MaxDailyHoursExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least {0} min break required for over {1}h work time ähnelt.
        /// </summary>
        internal static string MinBreakNotMet {
            get {
                return ResourceManager.GetString("MinBreakNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rest time under {0}h between shifts ähnelt.
        /// </summary>
        internal static string MinRestNotMet {
            get {
                return ResourceManager.GetString("MinRestNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mon ähnelt.
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monday ähnelt.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month balance ähnelt.
        /// </summary>
        internal static string MonthBalance {
            get {
                return ResourceManager.GetString("MonthBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month closed ähnelt.
        /// </summary>
        internal static string MonthLocked {
            get {
                return ResourceManager.GetString("MonthLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month overview ähnelt.
        /// </summary>
        internal static string MonthOverview {
            get {
                return ResourceManager.GetString("MonthOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start of work ähnelt.
        /// </summary>
        internal static string MorningReminder {
            get {
                return ResourceManager.GetString("MorningReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No entries ähnelt.
        /// </summary>
        internal static string NoEntries {
            get {
                return ResourceManager.GetString("NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No breaks recorded ähnelt.
        /// </summary>
        internal static string NoPauses {
            get {
                return ResourceManager.GetString("NoPauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime ähnelt.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime trend ähnelt.
        /// </summary>
        internal static string OvertimeTrend {
            get {
                return ResourceManager.GetString("OvertimeTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime warning ähnelt.
        /// </summary>
        internal static string OvertimeWarning {
            get {
                return ResourceManager.GetString("OvertimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warn after hours/week ähnelt.
        /// </summary>
        internal static string OvertimeWarningHours {
            get {
                return ResourceManager.GetString("OvertimeWarningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break duration (minutes) ähnelt.
        /// </summary>
        internal static string PauseMinutes {
            get {
                return ResourceManager.GetString("PauseMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaks ähnelt.
        /// </summary>
        internal static string Pauses {
            get {
                return ResourceManager.GetString("Pauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Period ähnelt.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium ähnelt.
        /// </summary>
        internal static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium active ähnelt.
        /// </summary>
        internal static string PremiumActive {
            get {
                return ResourceManager.GetString("PremiumActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium status ähnelt.
        /// </summary>
        internal static string PremiumStatus {
            get {
                return ResourceManager.GetString("PremiumStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase failed ähnelt.
        /// </summary>
        internal static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quarter ähnelt.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region ähnelt.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining ähnelt.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminders ähnelt.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore failed ähnelt.
        /// </summary>
        internal static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore purchases ähnelt.
        /// </summary>
        internal static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sat ähnelt.
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturday ähnelt.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save settings ähnelt.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start break ähnelt.
        /// </summary>
        internal static string StartPause {
            get {
                return ResourceManager.GetString("StartPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not started ähnelt.
        /// </summary>
        internal static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On break ähnelt.
        /// </summary>
        internal static string Status_OnBreak {
            get {
                return ResourceManager.GetString("Status_OnBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working ähnelt.
        /// </summary>
        internal static string Status_Working {
            get {
                return ResourceManager.GetString("Status_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sun ähnelt.
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sunday ähnelt.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target ähnelt.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design ähnelt.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This week ähnelt.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thu ähnelt.
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thursday ähnelt.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time entries ähnelt.
        /// </summary>
        internal static string TimeEntries {
            get {
                return ResourceManager.GetString("TimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total work time ähnelt.
        /// </summary>
        internal static string TotalWorkTime {
            get {
                return ResourceManager.GetString("TotalWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trial: {0} days left ähnelt.
        /// </summary>
        internal static string TrialDaysLeft {
            get {
                return ResourceManager.GetString("TrialDaysLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try Premium for free? ähnelt.
        /// </summary>
        internal static string TrialOfferTitle {
            get {
                return ResourceManager.GetString("TrialOfferTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 14 days free trial ähnelt.
        /// </summary>
        internal static string TrialOfferStart {
            get {
                return ResourceManager.GetString("TrialOfferStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy now ähnelt.
        /// </summary>
        internal static string TrialOfferBuyNow {
            get {
                return ResourceManager.GetString("TrialOfferBuyNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trial started! ähnelt.
        /// </summary>
        internal static string TrialStartedTitle {
            get {
                return ResourceManager.GetString("TrialStartedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You now have {0} days of Premium without ads. Enjoy! ähnelt.
        /// </summary>
        internal static string TrialStartedMessage {
            get {
                return ResourceManager.GetString("TrialStartedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Premium ähnelt.
        /// </summary>
        internal static string PurchaseOptionTitle {
            get {
                return ResourceManager.GetString("PurchaseOptionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly: €3.99/month ähnelt.
        /// </summary>
        internal static string PurchaseOptionMonthly {
            get {
                return ResourceManager.GetString("PurchaseOptionMonthly", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifetime: €19.99 (one-time) ähnelt.
        /// </summary>
        internal static string PurchaseOptionLifetime {
            get {
                return ResourceManager.GetString("PurchaseOptionLifetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase successful! Thank you for your support. ähnelt.
        /// </summary>
        internal static string PurchaseSuccess {
            get {
                return ResourceManager.GetString("PurchaseSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscription active ähnelt.
        /// </summary>
        internal static string HasSubscription {
            get {
                return ResourceManager.GetString("HasSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifetime Premium ähnelt.
        /// </summary>
        internal static string HasLifetime {
            get {
                return ResourceManager.GetString("HasLifetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tue ähnelt.
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tuesday ähnelt.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock month ähnelt.
        /// </summary>
        internal static string UnlockMonth {
            get {
                return ResourceManager.GetString("UnlockMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wed ähnelt.
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wednesday ähnelt.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly target ähnelt.
        /// </summary>
        internal static string WeeklyTarget {
            get {
                return ResourceManager.GetString("WeeklyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly work time ähnelt.
        /// </summary>
        internal static string WeeklyWorkTime {
            get {
                return ResourceManager.GetString("WeeklyWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week overview ähnelt.
        /// </summary>
        internal static string WeekOverview {
            get {
                return ResourceManager.GetString("WeekOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week progress ähnelt.
        /// </summary>
        internal static string WeekProgress {
            get {
                return ResourceManager.GetString("WeekProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work days ähnelt.
        /// </summary>
        internal static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Worked days ähnelt.
        /// </summary>
        internal static string WorkedDays {
            get {
                return ResourceManager.GetString("WorkedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time ähnelt.
        /// </summary>
        internal static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time ähnelt.
        /// </summary>
        internal static string WorkTimeSettings {
            get {
                return ResourceManager.GetString("WorkTimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show day details ähnelt.
        /// </summary>
        internal static string ShowDayDetails {
            get {
                return ResourceManager.GetString("ShowDayDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days this week ähnelt.
        /// </summary>
        internal static string DaysThisWeek {
            get {
                return ResourceManager.GetString("DaysThisWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charts ähnelt.
        /// </summary>
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table ähnelt.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work time table ähnelt.
        /// </summary>
        internal static string WorkTimeTable {
            get {
                return ResourceManager.GetString("WorkTimeTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly work time ähnelt.
        /// </summary>
        internal static string WeeklyWorkTimeChart {
            get {
                return ResourceManager.GetString("WeeklyWorkTimeChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime trend ähnelt.
        /// </summary>
        internal static string OvertimeTrendChart {
            get {
                return ResourceManager.GetString("OvertimeTrendChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average by weekday ähnelt.
        /// </summary>
        internal static string WeekdayAverage {
            get {
                return ResourceManager.GetString("WeekdayAverage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project distribution ähnelt.
        /// </summary>
        internal static string ProjectDistribution {
            get {
                return ResourceManager.GetString("ProjectDistribution", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employer distribution ähnelt.
        /// </summary>
        internal static string EmployerDistribution {
            get {
                return ResourceManager.GetString("EmployerDistribution", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breaks ähnelt.
        /// </summary>
        internal static string PauseStats {
            get {
                return ResourceManager.GetString("PauseStats", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation ähnelt.
        /// </summary>
        internal static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation days per year ähnelt.
        /// </summary>
        internal static string VacationDaysPerYear {
            get {
                return ResourceManager.GetString("VacationDaysPerYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default: 30 days ähnelt.
        /// </summary>
        internal static string VacationDefault {
            get {
                return ResourceManager.GetString("VacationDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual hours per day ähnelt.
        /// </summary>
        internal static string IndividualHoursPerDay {
            get {
                return ResourceManager.GetString("IndividualHoursPerDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select region ähnelt.
        /// </summary>
        internal static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved ähnelt.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings saved successfully ähnelt.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sick ähnelt.
        /// </summary>
        internal static string Sick {
            get {
                return ResourceManager.GetString("Sick", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holiday ähnelt.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg/day ähnelt.
        /// </summary>
        internal static string AvgPerDay {
            get {
                return ResourceManager.GetString("AvgPerDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work days ähnelt.
        /// </summary>
        internal static string WorkedDaysCount {
            get {
                return ResourceManager.GetString("WorkedDaysCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export as... ähnelt.
        /// </summary>
        internal static string ExportAs {
            get {
                return ResourceManager.GetString("ExportAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export successful ähnelt.
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export failed ähnelt.
        /// </summary>
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change status ähnelt.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show details ähnelt.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter vacation ähnelt.
        /// </summary>
        internal static string EnterVacation {
            get {
                return ResourceManager.GetString("EnterVacation", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation (multiple days) ähnelt.
        /// </summary>
        internal static string MultiDayVacation {
            get {
                return ResourceManager.GetString("MultiDayVacation", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report sick ähnelt.
        /// </summary>
        internal static string ReportSick {
            get {
                return ResourceManager.GetString("ReportSick", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset status ähnelt.
        /// </summary>
        internal static string ResetStatus {
            get {
                return ResourceManager.GetString("ResetStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter time: ähnelt.
        /// </summary>
        internal static string EnterTime {
            get {
                return ResourceManager.GetString("EnterTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid time format. ähnelt.
        /// </summary>
        internal static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit time ähnelt.
        /// </summary>
        internal static string EditTime {
            get {
                return ResourceManager.GetString("EditTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New time for {0}: ähnelt.
        /// </summary>
        internal static string NewTimeFor {
            get {
                return ResourceManager.GetString("NewTimeFor", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter vacation ähnelt.
        /// </summary>
        internal static string EnterVacationTitle {
            get {
                return ResourceManager.GetString("EnterVacationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many days? ähnelt.
        /// </summary>
        internal static string HowManyDays {
            get {
                return ResourceManager.GetString("HowManyDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of days ähnelt.
        /// </summary>
        internal static string NumberOfDays {
            get {
                return ResourceManager.GetString("NumberOfDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation entered ähnelt.
        /// </summary>
        internal static string VacationEntered {
            get {
                return ResourceManager.GetString("VacationEntered", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} vacation days from {1} have been entered. ähnelt.
        /// </summary>
        internal static string VacationDaysEnteredFormat {
            get {
                return ResourceManager.GetString("VacationDaysEnteredFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home office ähnelt.
        /// </summary>
        internal static string HomeOfficeTitle {
            get {
                return ResourceManager.GetString("HomeOfficeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional note: ähnelt.
        /// </summary>
        internal static string OptionalNotePrompt {
            get {
                return ResourceManager.GetString("OptionalNotePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die e.g. Project work ähnelt.
        /// </summary>
        internal static string NotePlaceholder {
            get {
                return ResourceManager.GetString("NotePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto breaks are calculated automatically. ähnelt.
        /// </summary>
        internal static string AutoBreakInfo {
            get {
                return ResourceManager.GetString("AutoBreakInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit break ähnelt.
        /// </summary>
        internal static string EditBreak {
            get {
                return ResourceManager.GetString("EditBreak", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break start time: ähnelt.
        /// </summary>
        internal static string BreakStartTime {
            get {
                return ResourceManager.GetString("BreakStartTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break end time: ähnelt.
        /// </summary>
        internal static string BreakEndTime {
            get {
                return ResourceManager.GetString("BreakEndTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to close {0}? ähnelt.
        /// </summary>
        internal static string CloseMonthConfirm {
            get {
                return ResourceManager.GetString("CloseMonthConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to unlock {0}? ähnelt.
        /// </summary>
        internal static string UnlockMonthConfirm {
            get {
                return ResourceManager.GetString("UnlockMonthConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock ähnelt.
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overtime compensation ähnelt.
        /// </summary>
        internal static string OvertimeCompensation {
            get {
                return ResourceManager.GetString("OvertimeCompensation", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special leave ähnelt.
        /// </summary>
        internal static string SpecialLeave {
            get {
                return ResourceManager.GetString("SpecialLeave", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die planned ähnelt.
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Premium feature ähnelt.
        /// </summary>
        internal static string PremiumFeature {
            get {
                return ResourceManager.GetString("PremiumFeature", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature requires Premium. ähnelt.
        /// </summary>
        internal static string PremiumRequired {
            get {
                return ResourceManager.GetString("PremiumRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note ähnelt.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected period contains no work days. ähnelt.
        /// </summary>
        internal static string NoWorkDaysInPeriod {
            get {
                return ResourceManager.GetString("NoWorkDaysInPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete vacation? ähnelt.
        /// </summary>
        internal static string DeleteVacationConfirm {
            get {
                return ResourceManager.GetString("DeleteVacationConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this vacation? ähnelt.
        /// </summary>
        internal static string DeleteVacationMessage {
            get {
                return ResourceManager.GetString("DeleteVacationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vacation days for this year: ähnelt.
        /// </summary>
        internal static string VacationDaysInfo {
            get {
                return ResourceManager.GetString("VacationDaysInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carry over days ähnelt.
        /// </summary>
        internal static string CarryOverDays {
            get {
                return ResourceManager.GetString("CarryOverDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days from {1} have been carried over. ähnelt.
        /// </summary>
        internal static string DaysCarriedOver {
            get {
                return ResourceManager.GetString("DaysCarriedOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No remaining days from {0} to carry over. ähnelt.
        /// </summary>
        internal static string NoDaysToCarryOver {
            get {
                return ResourceManager.GetString("NoDaysToCarryOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illness ähnelt.
        /// </summary>
        internal static string Illness {
            get {
                return ResourceManager.GetString("Illness", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unpaid leave ähnelt.
        /// </summary>
        internal static string UnpaidLeave {
            get {
                return ResourceManager.GetString("UnpaidLeave", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual Hours ähnelt.
        /// </summary>
        internal static string ChartActualHours {
            get {
                return ResourceManager.GetString("ChartActualHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target ({0}h) ähnelt.
        /// </summary>
        internal static string ChartTargetFormat {
            get {
                return ResourceManager.GetString("ChartTargetFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        internal static string ChartHours {
            get {
                return ResourceManager.GetString("ChartHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily ähnelt.
        /// </summary>
        internal static string ChartDaily {
            get {
                return ResourceManager.GetString("ChartDaily", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cumulative ähnelt.
        /// </summary>
        internal static string ChartCumulative {
            get {
                return ResourceManager.GetString("ChartCumulative", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg. Hours ähnelt.
        /// </summary>
        internal static string ChartAvgHours {
            get {
                return ResourceManager.GetString("ChartAvgHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work hours ähnelt.
        /// </summary>
        internal static string ChartWorkHours {
            get {
                return ResourceManager.GetString("ChartWorkHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cum. balance ähnelt.
        /// </summary>
        internal static string ChartCumulativeBalance {
            get {
                return ResourceManager.GetString("ChartCumulativeBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string TableDate {
            get {
                return ResourceManager.GetString("TableDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string TableStatus {
            get {
                return ResourceManager.GetString("TableStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In ähnelt.
        /// </summary>
        internal static string TableCheckIn {
            get {
                return ResourceManager.GetString("TableCheckIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Out ähnelt.
        /// </summary>
        internal static string TableCheckOut {
            get {
                return ResourceManager.GetString("TableCheckOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work ähnelt.
        /// </summary>
        internal static string TableWork {
            get {
                return ResourceManager.GetString("TableWork", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string TablePause {
            get {
                return ResourceManager.GetString("TablePause", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        internal static string TableBalance {
            get {
                return ResourceManager.GetString("TableBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        internal static string ShiftOff {
            get {
                return ResourceManager.GetString("ShiftOff", resourceCulture);
            }
        }

        internal static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }

        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }

        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }

        internal static string ErrorOpenUrl {
            get {
                return ResourceManager.GetString("ErrorOpenUrl", resourceCulture);
            }
        }

        internal static string DayStatus_Training {
            get {
                return ResourceManager.GetString("DayStatus_Training", resourceCulture);
            }
        }

        internal static string DayStatus_CompensatoryTime {
            get {
                return ResourceManager.GetString("DayStatus_CompensatoryTime", resourceCulture);
            }
        }

        internal static string CalendarCreatedBy {
            get {
                return ResourceManager.GetString("CalendarCreatedBy", resourceCulture);
            }
        }

        internal static string CalendarAutoBreak {
            get {
                return ResourceManager.GetString("CalendarAutoBreak", resourceCulture);
            }
        }

        internal static string PdfExportPremium {
            get {
                return ResourceManager.GetString("PdfExportPremium", resourceCulture);
            }
        }

        internal static string ExportFailedMessage {
            get {
                return ResourceManager.GetString("ExportFailedMessage", resourceCulture);
            }
        }

        internal static string RemainingDays {
            get {
                return ResourceManager.GetString("RemainingDays", resourceCulture);
            }
        }

        internal static string ThemeMidnight {
            get {
                return ResourceManager.GetString("ThemeMidnight", resourceCulture);
            }
        }

        internal static string ThemeMidnightDesc {
            get {
                return ResourceManager.GetString("ThemeMidnightDesc", resourceCulture);
            }
        }

        internal static string ThemeAurora {
            get {
                return ResourceManager.GetString("ThemeAurora", resourceCulture);
            }
        }

        internal static string ThemeAuroraDesc {
            get {
                return ResourceManager.GetString("ThemeAuroraDesc", resourceCulture);
            }
        }

        internal static string ThemeDaylight {
            get {
                return ResourceManager.GetString("ThemeDaylight", resourceCulture);
            }
        }

        internal static string ThemeDaylightDesc {
            get {
                return ResourceManager.GetString("ThemeDaylightDesc", resourceCulture);
            }
        }

        internal static string ThemeForest {
            get {
                return ResourceManager.GetString("ThemeForest", resourceCulture);
            }
        }

        internal static string ThemeForestDesc {
            get {
                return ResourceManager.GetString("ThemeForestDesc", resourceCulture);
            }
        }

        internal static string SetStatus {
            get {
                return ResourceManager.GetString("SetStatus", resourceCulture);
            }
        }

        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }

        internal static string WorkDaysFormat {
            get {
                return ResourceManager.GetString("WorkDaysFormat", resourceCulture);
            }
        }

        // Rewarded Ads
        internal static string PremiumFeatureTitle {
            get {
                return ResourceManager.GetString("PremiumFeatureTitle", resourceCulture);
            }
        }

        internal static string PremiumFeatureDesc {
            get {
                return ResourceManager.GetString("PremiumFeatureDesc", resourceCulture);
            }
        }

        internal static string WatchVideoOnce {
            get {
                return ResourceManager.GetString("WatchVideoOnce", resourceCulture);
            }
        }

        internal static string BuyPremiumUnlimited {
            get {
                return ResourceManager.GetString("BuyPremiumUnlimited", resourceCulture);
            }
        }

        internal static string VideoRewardSuccess {
            get {
                return ResourceManager.GetString("VideoRewardSuccess", resourceCulture);
            }
        }

        internal static string VideoAdFailed {
            get {
                return ResourceManager.GetString("VideoAdFailed", resourceCulture);
            }
        }

        internal static string AdVideoNotAvailableTitle {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableTitle", resourceCulture);
            }
        }

        internal static string AdVideoNotAvailableMessage {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableMessage", resourceCulture);
            }
        }
    }
}
