//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomberBlast.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BomberBlast.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // App Name
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        // Menu
        internal static string StoryMode {
            get {
                return ResourceManager.GetString("StoryMode", resourceCulture);
            }
        }

        internal static string ArcadeMode {
            get {
                return ResourceManager.GetString("ArcadeMode", resourceCulture);
            }
        }

        internal static string QuickPlay {
            get {
                return ResourceManager.GetString("QuickPlay", resourceCulture);
            }
        }

        internal static string HighScores {
            get {
                return ResourceManager.GetString("HighScores", resourceCulture);
            }
        }

        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }

        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        // Game
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }

        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }

        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }

        internal static string RestartLevel {
            get {
                return ResourceManager.GetString("RestartLevel", resourceCulture);
            }
        }

        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }

        internal static string QuitToMenu {
            get {
                return ResourceManager.GetString("QuitToMenu", resourceCulture);
            }
        }

        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }

        internal static string LevelComplete {
            get {
                return ResourceManager.GetString("LevelComplete", resourceCulture);
            }
        }

        internal static string NewHighScore {
            get {
                return ResourceManager.GetString("NewHighScore", resourceCulture);
            }
        }

        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }

        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }

        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }

        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        internal static string Wave {
            get {
                return ResourceManager.GetString("Wave", resourceCulture);
            }
        }

        internal static string TimeBonus {
            get {
                return ResourceManager.GetString("TimeBonus", resourceCulture);
            }
        }

        // Level Select
        internal static string SelectLevel {
            get {
                return ResourceManager.GetString("SelectLevel", resourceCulture);
            }
        }

        internal static string CompletedLevels {
            get {
                return ResourceManager.GetString("CompletedLevels", resourceCulture);
            }
        }

        internal static string TotalStars {
            get {
                return ResourceManager.GetString("TotalStars", resourceCulture);
            }
        }

        // High Scores
        internal static string NoHighScoresYet {
            get {
                return ResourceManager.GetString("NoHighScoresYet", resourceCulture);
            }
        }

        internal static string PlayArcadeToScore {
            get {
                return ResourceManager.GetString("PlayArcadeToScore", resourceCulture);
            }
        }

        internal static string WaveFormat {
            get {
                return ResourceManager.GetString("WaveFormat", resourceCulture);
            }
        }

        internal static string ScoreFormat {
            get {
                return ResourceManager.GetString("ScoreFormat", resourceCulture);
            }
        }

        internal static string HighScoreWaveDate {
            get {
                return ResourceManager.GetString("HighScoreWaveDate", resourceCulture);
            }
        }

        internal static string TapToResume {
            get {
                return ResourceManager.GetString("TapToResume", resourceCulture);
            }
        }

        internal static string FinalScore {
            get {
                return ResourceManager.GetString("FinalScore", resourceCulture);
            }
        }

        internal static string WaveReached {
            get {
                return ResourceManager.GetString("WaveReached", resourceCulture);
            }
        }

        internal static string WaveOverlay {
            get {
                return ResourceManager.GetString("WaveOverlay", resourceCulture);
            }
        }

        internal static string StageOverlay {
            get {
                return ResourceManager.GetString("StageOverlay", resourceCulture);
            }
        }

        internal static string TimeBonusFormat {
            get {
                return ResourceManager.GetString("TimeBonusFormat", resourceCulture);
            }
        }

        internal static string SwipeHint {
            get {
                return ResourceManager.GetString("SwipeHint", resourceCulture);
            }
        }

        internal static string LevelFormat {
            get {
                return ResourceManager.GetString("LevelFormat", resourceCulture);
            }
        }

        // Settings
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }

        internal static string ControlsSection {
            get {
                return ResourceManager.GetString("ControlsSection", resourceCulture);
            }
        }

        internal static string SoundSection {
            get {
                return ResourceManager.GetString("SoundSection", resourceCulture);
            }
        }

        internal static string PremiumSection {
            get {
                return ResourceManager.GetString("PremiumSection", resourceCulture);
            }
        }

        internal static string DataSection {
            get {
                return ResourceManager.GetString("DataSection", resourceCulture);
            }
        }

        internal static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }

        internal static string FloatingJoystick {
            get {
                return ResourceManager.GetString("FloatingJoystick", resourceCulture);
            }
        }

        internal static string FloatingJoystickRecommended {
            get {
                return ResourceManager.GetString("FloatingJoystickRecommended", resourceCulture);
            }
        }

        internal static string SwipeGestures {
            get {
                return ResourceManager.GetString("SwipeGestures", resourceCulture);
            }
        }

        internal static string ClassicDPad {
            get {
                return ResourceManager.GetString("ClassicDPad", resourceCulture);
            }
        }

        internal static string JoystickSize {
            get {
                return ResourceManager.GetString("JoystickSize", resourceCulture);
            }
        }

        internal static string JoystickOpacity {
            get {
                return ResourceManager.GetString("JoystickOpacity", resourceCulture);
            }
        }

        internal static string HapticFeedback {
            get {
                return ResourceManager.GetString("HapticFeedback", resourceCulture);
            }
        }

        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }

        internal static string SoundEffects {
            get {
                return ResourceManager.GetString("SoundEffects", resourceCulture);
            }
        }

        internal static string SfxVolume {
            get {
                return ResourceManager.GetString("SfxVolume", resourceCulture);
            }
        }

        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }

        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }

        internal static string TrialDaysRemaining {
            get {
                return ResourceManager.GetString("TrialDaysRemaining", resourceCulture);
            }
        }

        internal static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }

        internal static string TrialAvailable {
            get {
                return ResourceManager.GetString("TrialAvailable", resourceCulture);
            }
        }

        internal static string PremiumActive {
            get {
                return ResourceManager.GetString("PremiumActive", resourceCulture);
            }
        }

        internal static string BuyPremium {
            get {
                return ResourceManager.GetString("BuyPremium", resourceCulture);
            }
        }

        internal static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }

        internal static string RemoveAdsDescription {
            get {
                return ResourceManager.GetString("RemoveAdsDescription", resourceCulture);
            }
        }

        internal static string ResetProgress {
            get {
                return ResourceManager.GetString("ResetProgress", resourceCulture);
            }
        }

        internal static string ClearHighScores {
            get {
                return ResourceManager.GetString("ClearHighScores", resourceCulture);
            }
        }

        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }

        internal static string ResetProgressTitle {
            get {
                return ResourceManager.GetString("ResetProgressTitle", resourceCulture);
            }
        }

        internal static string ResetProgressMessage {
            get {
                return ResourceManager.GetString("ResetProgressMessage", resourceCulture);
            }
        }

        internal static string ResetProgressConfirm {
            get {
                return ResourceManager.GetString("ResetProgressConfirm", resourceCulture);
            }
        }

        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        internal static string ProgressResetTitle {
            get {
                return ResourceManager.GetString("ProgressResetTitle", resourceCulture);
            }
        }

        internal static string ProgressResetMessage {
            get {
                return ResourceManager.GetString("ProgressResetMessage", resourceCulture);
            }
        }

        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        internal static string ClearScoresTitle {
            get {
                return ResourceManager.GetString("ClearScoresTitle", resourceCulture);
            }
        }

        internal static string ClearScoresMessage {
            get {
                return ResourceManager.GetString("ClearScoresMessage", resourceCulture);
            }
        }

        internal static string ClearScoresConfirm {
            get {
                return ResourceManager.GetString("ClearScoresConfirm", resourceCulture);
            }
        }

        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        internal static string ScoresClearedTitle {
            get {
                return ResourceManager.GetString("ScoresClearedTitle", resourceCulture);
            }
        }

        internal static string ScoresClearedMessage {
            get {
                return ResourceManager.GetString("ScoresClearedMessage", resourceCulture);
            }
        }

        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }

        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }

        internal static string PremiumActivated {
            get {
                return ResourceManager.GetString("PremiumActivated", resourceCulture);
            }
        }

        internal static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }

        internal static string PurchaseFailedMessage {
            get {
                return ResourceManager.GetString("PurchaseFailedMessage", resourceCulture);
            }
        }

        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        internal static string Restored {
            get {
                return ResourceManager.GetString("Restored", resourceCulture);
            }
        }

        internal static string PurchaseRestored {
            get {
                return ResourceManager.GetString("PurchaseRestored", resourceCulture);
            }
        }

        internal static string NoPurchases {
            get {
                return ResourceManager.GetString("NoPurchases", resourceCulture);
            }
        }

        internal static string NoPurchasesMessage {
            get {
                return ResourceManager.GetString("NoPurchasesMessage", resourceCulture);
            }
        }

        internal static string NoPurchasesFound {
            get {
                return ResourceManager.GetString("NoPurchasesFound", resourceCulture);
            }
        }

        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }

        internal static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }

        internal static string ProgressResetDone {
            get {
                return ResourceManager.GetString("ProgressResetDone", resourceCulture);
            }
        }

        internal static string ScoresClearedDone {
            get {
                return ResourceManager.GetString("ScoresClearedDone", resourceCulture);
            }
        }

        internal static string ControlFloatingJoystick {
            get {
                return ResourceManager.GetString("ControlFloatingJoystick", resourceCulture);
            }
        }

        internal static string ControlSwipe {
            get {
                return ResourceManager.GetString("ControlSwipe", resourceCulture);
            }
        }

        internal static string ControlDPad {
            get {
                return ResourceManager.GetString("ControlDPad", resourceCulture);
            }
        }

        internal static string PremiumDescription {
            get {
                return ResourceManager.GetString("PremiumDescription", resourceCulture);
            }
        }

        // Help Page
        internal static string HowToPlay {
            get {
                return ResourceManager.GetString("HowToPlay", resourceCulture);
            }
        }

        internal static string HowToPlayDesc {
            get {
                return ResourceManager.GetString("HowToPlayDesc", resourceCulture);
            }
        }

        internal static string ControlsHelp {
            get {
                return ResourceManager.GetString("ControlsHelp", resourceCulture);
            }
        }

        internal static string ControlsHelpDesc {
            get {
                return ResourceManager.GetString("ControlsHelpDesc", resourceCulture);
            }
        }

        internal static string PowerUps {
            get {
                return ResourceManager.GetString("PowerUps", resourceCulture);
            }
        }

        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }

        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }

        internal static string TipsDesc {
            get {
                return ResourceManager.GetString("TipsDesc", resourceCulture);
            }
        }

        // Enemies
        internal static string Enemy_Ballom {
            get {
                return ResourceManager.GetString("Enemy_Ballom", resourceCulture);
            }
        }

        internal static string Enemy_Ballom_Desc {
            get {
                return ResourceManager.GetString("Enemy_Ballom_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Onil {
            get {
                return ResourceManager.GetString("Enemy_Onil", resourceCulture);
            }
        }

        internal static string Enemy_Onil_Desc {
            get {
                return ResourceManager.GetString("Enemy_Onil_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Doll {
            get {
                return ResourceManager.GetString("Enemy_Doll", resourceCulture);
            }
        }

        internal static string Enemy_Doll_Desc {
            get {
                return ResourceManager.GetString("Enemy_Doll_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Minvo {
            get {
                return ResourceManager.GetString("Enemy_Minvo", resourceCulture);
            }
        }

        internal static string Enemy_Minvo_Desc {
            get {
                return ResourceManager.GetString("Enemy_Minvo_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Kondoria {
            get {
                return ResourceManager.GetString("Enemy_Kondoria", resourceCulture);
            }
        }

        internal static string Enemy_Kondoria_Desc {
            get {
                return ResourceManager.GetString("Enemy_Kondoria_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Ovapi {
            get {
                return ResourceManager.GetString("Enemy_Ovapi", resourceCulture);
            }
        }

        internal static string Enemy_Ovapi_Desc {
            get {
                return ResourceManager.GetString("Enemy_Ovapi_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Pass {
            get {
                return ResourceManager.GetString("Enemy_Pass", resourceCulture);
            }
        }

        internal static string Enemy_Pass_Desc {
            get {
                return ResourceManager.GetString("Enemy_Pass_Desc", resourceCulture);
            }
        }

        internal static string Enemy_Pontan {
            get {
                return ResourceManager.GetString("Enemy_Pontan", resourceCulture);
            }
        }

        internal static string Enemy_Pontan_Desc {
            get {
                return ResourceManager.GetString("Enemy_Pontan_Desc", resourceCulture);
            }
        }

        // Power-ups
        internal static string PowerUp_BombUp {
            get {
                return ResourceManager.GetString("PowerUp_BombUp", resourceCulture);
            }
        }

        internal static string PowerUp_BombUp_Desc {
            get {
                return ResourceManager.GetString("PowerUp_BombUp_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Fire {
            get {
                return ResourceManager.GetString("PowerUp_Fire", resourceCulture);
            }
        }

        internal static string PowerUp_Fire_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Fire_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Speed {
            get {
                return ResourceManager.GetString("PowerUp_Speed", resourceCulture);
            }
        }

        internal static string PowerUp_Speed_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Speed_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Wallpass {
            get {
                return ResourceManager.GetString("PowerUp_Wallpass", resourceCulture);
            }
        }

        internal static string PowerUp_Wallpass_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Wallpass_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Detonator {
            get {
                return ResourceManager.GetString("PowerUp_Detonator", resourceCulture);
            }
        }

        internal static string PowerUp_Detonator_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Detonator_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Bombpass {
            get {
                return ResourceManager.GetString("PowerUp_Bombpass", resourceCulture);
            }
        }

        internal static string PowerUp_Bombpass_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Bombpass_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Flamepass {
            get {
                return ResourceManager.GetString("PowerUp_Flamepass", resourceCulture);
            }
        }

        internal static string PowerUp_Flamepass_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Flamepass_Desc", resourceCulture);
            }
        }

        internal static string PowerUp_Mystery {
            get {
                return ResourceManager.GetString("PowerUp_Mystery", resourceCulture);
            }
        }

        internal static string PowerUp_Mystery_Desc {
            get {
                return ResourceManager.GetString("PowerUp_Mystery_Desc", resourceCulture);
            }
        }

        // Languages
        internal static string LanguageSection {
            get {
                return ResourceManager.GetString("LanguageSection", resourceCulture);
            }
        }

        internal static string LanguageDE {
            get {
                return ResourceManager.GetString("LanguageDE", resourceCulture);
            }
        }

        internal static string LanguageEN {
            get {
                return ResourceManager.GetString("LanguageEN", resourceCulture);
            }
        }

        internal static string LanguageES {
            get {
                return ResourceManager.GetString("LanguageES", resourceCulture);
            }
        }

        internal static string LanguageFR {
            get {
                return ResourceManager.GetString("LanguageFR", resourceCulture);
            }
        }

        internal static string LanguageIT {
            get {
                return ResourceManager.GetString("LanguageIT", resourceCulture);
            }
        }

        internal static string LanguagePT {
            get {
                return ResourceManager.GetString("LanguagePT", resourceCulture);
            }
        }

        // Input Controls
        internal static string InputFloatingJoystick {
            get {
                return ResourceManager.GetString("InputFloatingJoystick", resourceCulture);
            }
        }

        internal static string JoystickModeFixed {
            get {
                return ResourceManager.GetString("JoystickModeFixed", resourceCulture);
            }
        }

        // Shop UI
        internal static string ShopTitle {
            get {
                return ResourceManager.GetString("ShopTitle", resourceCulture);
            }
        }

        internal static string ShopBuy {
            get {
                return ResourceManager.GetString("ShopBuy", resourceCulture);
            }
        }

        internal static string ShopMaxed {
            get {
                return ResourceManager.GetString("ShopMaxed", resourceCulture);
            }
        }

        internal static string ShopNotEnoughCoins {
            get {
                return ResourceManager.GetString("ShopNotEnoughCoins", resourceCulture);
            }
        }

        internal static string SectionStartUpgrades {
            get {
                return ResourceManager.GetString("SectionStartUpgrades", resourceCulture);
            }
        }

        internal static string SectionScoreBooster {
            get {
                return ResourceManager.GetString("SectionScoreBooster", resourceCulture);
            }
        }

        internal static string UpgradeLevelFormat {
            get {
                return ResourceManager.GetString("UpgradeLevelFormat", resourceCulture);
            }
        }

        internal static string UpgradeStartBombs {
            get {
                return ResourceManager.GetString("UpgradeStartBombs", resourceCulture);
            }
        }

        internal static string UpgradeStartBombsDesc {
            get {
                return ResourceManager.GetString("UpgradeStartBombsDesc", resourceCulture);
            }
        }

        internal static string UpgradeStartFire {
            get {
                return ResourceManager.GetString("UpgradeStartFire", resourceCulture);
            }
        }

        internal static string UpgradeStartFireDesc {
            get {
                return ResourceManager.GetString("UpgradeStartFireDesc", resourceCulture);
            }
        }

        internal static string UpgradeStartSpeed {
            get {
                return ResourceManager.GetString("UpgradeStartSpeed", resourceCulture);
            }
        }

        internal static string UpgradeStartSpeedDesc {
            get {
                return ResourceManager.GetString("UpgradeStartSpeedDesc", resourceCulture);
            }
        }

        internal static string UpgradeExtraLives {
            get {
                return ResourceManager.GetString("UpgradeExtraLives", resourceCulture);
            }
        }

        internal static string UpgradeExtraLivesDesc {
            get {
                return ResourceManager.GetString("UpgradeExtraLivesDesc", resourceCulture);
            }
        }

        internal static string UpgradeScoreMultiplier {
            get {
                return ResourceManager.GetString("UpgradeScoreMultiplier", resourceCulture);
            }
        }

        internal static string UpgradeScoreMultiplierDesc {
            get {
                return ResourceManager.GetString("UpgradeScoreMultiplierDesc", resourceCulture);
            }
        }

        internal static string UpgradeTimeBonus {
            get {
                return ResourceManager.GetString("UpgradeTimeBonus", resourceCulture);
            }
        }

        internal static string UpgradeTimeBonusDesc {
            get {
                return ResourceManager.GetString("UpgradeTimeBonusDesc", resourceCulture);
            }
        }

        // GameOver UI
        internal static string CoinsEarned {
            get {
                return ResourceManager.GetString("CoinsEarned", resourceCulture);
            }
        }

        internal static string DoubleCoins {
            get {
                return ResourceManager.GetString("DoubleCoins", resourceCulture);
            }
        }

        internal static string CoinsDoubled {
            get {
                return ResourceManager.GetString("CoinsDoubled", resourceCulture);
            }
        }

        internal static string ContinueGame {
            get {
                return ResourceManager.GetString("ContinueGame", resourceCulture);
            }
        }

        // Level Select
        internal static string WorldFormat {
            get {
                return ResourceManager.GetString("WorldFormat", resourceCulture);
            }
        }

        internal static string WorldLocked {
            get {
                return ResourceManager.GetString("WorldLocked", resourceCulture);
            }
        }

        internal static string WorldForest {
            get {
                return ResourceManager.GetString("WorldForest", resourceCulture);
            }
        }

        internal static string WorldIndustrial {
            get {
                return ResourceManager.GetString("WorldIndustrial", resourceCulture);
            }
        }

        internal static string WorldCavern {
            get {
                return ResourceManager.GetString("WorldCavern", resourceCulture);
            }
        }

        internal static string WorldSky {
            get {
                return ResourceManager.GetString("WorldSky", resourceCulture);
            }
        }

        internal static string WorldInferno {
            get {
                return ResourceManager.GetString("WorldInferno", resourceCulture);
            }
        }

        // Rewarded Ads
        internal static string PowerUpBoost {
            get {
                return ResourceManager.GetString("PowerUpBoost", resourceCulture);
            }
        }

        internal static string PowerUpBoostDesc {
            get {
                return ResourceManager.GetString("PowerUpBoostDesc", resourceCulture);
            }
        }

        internal static string BoostSpeed {
            get {
                return ResourceManager.GetString("BoostSpeed", resourceCulture);
            }
        }

        internal static string BoostFire {
            get {
                return ResourceManager.GetString("BoostFire", resourceCulture);
            }
        }

        internal static string BoostBomb {
            get {
                return ResourceManager.GetString("BoostBomb", resourceCulture);
            }
        }

        internal static string WatchVideo {
            get {
                return ResourceManager.GetString("WatchVideo", resourceCulture);
            }
        }

        internal static string WithoutBoost {
            get {
                return ResourceManager.GetString("WithoutBoost", resourceCulture);
            }
        }

        internal static string SkipLevel {
            get {
                return ResourceManager.GetString("SkipLevel", resourceCulture);
            }
        }

        internal static string SkipLevelInfo {
            get {
                return ResourceManager.GetString("SkipLevelInfo", resourceCulture);
            }
        }

        internal static string WatchVideoBoost {
            get {
                return ResourceManager.GetString("WatchVideoBoost", resourceCulture);
            }
        }

        // Score Double
        internal static string ScoreDoubleTitle {
            get {
                return ResourceManager.GetString("ScoreDoubleTitle", resourceCulture);
            }
        }

        internal static string ScoreDoubleDesc {
            get {
                return ResourceManager.GetString("ScoreDoubleDesc", resourceCulture);
            }
        }

        internal static string WatchVideoDouble {
            get {
                return ResourceManager.GetString("WatchVideoDouble", resourceCulture);
            }
        }

        internal static string ContinueWithout {
            get {
                return ResourceManager.GetString("ContinueWithout", resourceCulture);
            }
        }

        // Ad Unavailable
        internal static string AdVideoNotAvailableTitle {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableTitle", resourceCulture);
            }
        }

        internal static string AdVideoNotAvailableMessage {
            get {
                return ResourceManager.GetString("AdVideoNotAvailableMessage", resourceCulture);
            }
        }

        // Tutorial
        internal static string TutorialMove {
            get {
                return ResourceManager.GetString("TutorialMove", resourceCulture);
            }
        }

        internal static string TutorialBomb {
            get {
                return ResourceManager.GetString("TutorialBomb", resourceCulture);
            }
        }

        internal static string TutorialHide {
            get {
                return ResourceManager.GetString("TutorialHide", resourceCulture);
            }
        }

        internal static string TutorialPowerUp {
            get {
                return ResourceManager.GetString("TutorialPowerUp", resourceCulture);
            }
        }

        internal static string TutorialDefeatEnemies {
            get {
                return ResourceManager.GetString("TutorialDefeatEnemies", resourceCulture);
            }
        }

        internal static string TutorialExit {
            get {
                return ResourceManager.GetString("TutorialExit", resourceCulture);
            }
        }

        internal static string TutorialSkip {
            get {
                return ResourceManager.GetString("TutorialSkip", resourceCulture);
            }
        }

        // Back-Navigation
        internal static string PressBackAgainToExit {
            get {
                return ResourceManager.GetString("PressBackAgainToExit", resourceCulture);
            }
        }

        internal static string ReplayTutorial {
            get {
                return ResourceManager.GetString("ReplayTutorial", resourceCulture);
            }
        }
    }
}
